### ISSUE TITLE
Possibility to enable the mc '--insecure' flag

### ISSUE THREAD

**Issue by andornemeth** [offen/docker-volume-backup#1]
Enabling the '--insecure' flag would provide the flexibility to work with self signed Minio TLS server certificates.

**Comment by m90** [comment]
It'd probably be the most flexible thing to do to create a new config parameter that is passed through to all `mc` parameters, something like `MC_EXTRA_FLAGS` or similar.

If you want to add this I am happy to review and merge a PR, otherwise I should be able to do this myself soonish.

**Comment by m90** [comment]
This is now released in `offen/docker-volume-backup:v1.1.0`. You can pass `MC_GLOBAL_OPTIONS` as described here: https://docs.min.io/docs/minio-client-complete-guide.html
