### ISSUE TITLE
s3 forcePathStyle option in env

### ISSUE THREAD

**Issue by sfalihi** [offen/docker-volume-backup#110]
how to connect to s3 custom server that doesn't use bucket name as subdomain (but as path)? 
(s3 js client-side lib has an option called forcePathStyle for that purpose)

**Comment by m90** [comment]
I'm not entirely sure I understand your question correctly, but I think you could be using the `AWS_S3_PATH` option to append any path to the domain serving your S3 storage?

**Comment by sfalihi** [comment]
when you try to connect to s3 endpoint there is 2 possibility for connecting to bucket: 
1. as subdomain (default option)
2. as path

forexample if your s3 endpoint is s3.example.com and your bucket name is buckek1, it can connect in two possible ways (based on forcePathStyle option in official "js" library):
1. bucket1.s3.example.com
2. s3.example.com/bucket1

i think this library just use first option and will append bucket name to endpoint as subdomain to connect (its default option also). but what about second option?

i will try using AWS_S3_PATH somehow and see if it works.

**Comment by m90** [comment]
I'm using this tool to upload backups to a MinIO server I deployed myself for a long time now and I never set up per-bucket subdomains so I am pretty sure the use case you describe is supported somehow. I do not have to use AWS_S3_PATH for that to work either though.

Could you share more details about your configuration and the backup target you are trying to use so we can figure out what's going on?

**Comment by sfalihi** [comment]
you were right, unlike s3 js lib that append bucket_name as subdomain as default, your library doesnt do that. 

this ENV worked for me:
  AWS_ENDPOINT="s3.example.net"
  AWS_S3_BUCKET_NAME="BUCKET_NAME"
  ***AWS_S3_PATH="BUCKET_NAME/[extra path if needed]"
