### ISSUE TITLE
Add custom headers for S3

### ISSUE THREAD

**Issue by rwanito** [offen/docker-volume-backup#116]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**

I would like to add the headers support for S3 (ex: cold storage).
For example : `x-amz-storage-class` to GLACIER or STANDARD.
I'm not a go dev, so I prefer to let someone stronger than me here :p !

Thanks !

**Comment by m90** [comment]
This image is using the MinIO Golang SDK and it seems it does not allow setting headers like you propose but instead defines its own `PutObjectOptions`: https://github.com/minio/docs/blob/master/source/sdk/go/API.md#putobjectctx-contextcontext-bucketname-objectname-string-reader-ioreader-objectsize-int64opts-putobjectoptions-info-uploadinfo-err-error

I wouldn't be opposed to someone adding more of these options if it makes sense though. What would need to happen is:
- add the option to the `config` struct, preferrably with an `AWS_S3_` prefix: https://github.com/offen/docker-volume-backup/blob/c2a8cc92fcfc05e974df4656f024161cdd464c40/cmd/backup/config.go#L14-L58
- pass the value to the Minio Client here: https://github.com/offen/docker-volume-backup/blob/c2a8cc92fcfc05e974df4656f024161cdd464c40/cmd/backup/script.go#L548-L555
- add docs

---

> I'm not a go dev, so I prefer to let someone stronger than me here :p !

This repo has seen great feature contributions by first timers already, so don't be hesitant to try. Go isn't really that hard to pick up.

**Comment by m90** [comment]
Let me know if you need any help or input with that.
