### ISSUE TITLE
crond logging goes to the bit bucket

### ISSUE THREAD

**Issue by simmonmt** [offen/docker-volume-backup#117]
* **I'm submitting a ...**
  - [ X ] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**

You launch crond with `-f -l 8`. crond defaults to logging to syslog, so even though you've requested logging (`-l 8`) the messages all seem to get discarded since syslogd isn't running in the container. Consider `-d 8` instead, which would log to stderr and would thus show up in `docker container logs`.

* **What is the motivation / use case for changing the behavior?**

When debugging timezone issues (among other things), I really want to see some record that the cron job has actually launched. There's no such indication currently.

If disk space consumption by logs is a concern, perhaps just add an environment variable that'll let me pass extra flags to crond?

* **Please tell us about your environment:**
  
  - Image version: latest tag, dated 2022-06-17T09:39:39
  - Docker version: 20.10.17
  - docker-compose version: 1.29.2

**Comment by simmonmt** [comment]
... also for debugging user errors like incorrectly-specified cron specs

**Comment by m90** [comment]
> When debugging timezone issues (among other things), I really want to see some record that the cron job has actually launched. There's no such indication currently.

I'm not sure I understand your question entirely yet. The output of the command running in the container is forwarded to whatever log driver you have configured Docker to use. For example I use the following configuration on the host I am running this image:

```yml
    logging:
      driver: syslog
      options:
        tag: backup
```

and will see lines like this in the _host_'s syslog:

```
Jul  4 04:00:02 some-host backup[632]: time="2022-07-04T04:00:02+02:00" level=info msg="Finished running backup tasks."
```

I've also seen quite a few people pasting log output in the issues here so at least the command's output should be forwarded to Docker as intended. If your question is about the output of the `crond` command itself I have to admit I am not sure, does it even log anything unless it fails to start up?

**Comment by m90** [comment]
Ah yeah, good old quoted env vars. This happens a lot, although I think this is docker-compose doing weird stuff, not yaml. I can recommend adoption object notation for the `env` key which lets you quote things like a caveman if you want to.

Coming back to the original issue: thanks for explaining, that makes sense and is definitely to be considered a bug. Using `-d` sounds like the proper fix too, would you mind opening a PR with that change? I'd also say logging the timezone info in the entrypoint script shouldn't hurt anyone so feel free to add this as well.

**Comment by m90** [comment]
This is the compose issue if you're interested in understanding what's going on https://github.com/docker/compose/issues/2854

**Comment by m90** [comment]
Also related: https://github.com/offen/docker-volume-backup/issues/84

**Comment by simmonmt** [comment]
Thanks! Sorry I didn't get a chance to send you a pr myself
