### ISSUE TITLE
Get the name of the docker compose project in notification template via environment variable?

### ISSUE THREAD

**Issue by akash07k** [offen/docker-volume-backup#118]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**
No way to retrieve the name of the compose project or any other environment variable in notification template.

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**
For example,
I have many docker compose projects and I'm using this image with all of those projects individually to take the backups.
Now the thing is that I want to define only 1 notification template which can send me the notifications by including the project/container names in the notification subject/body.
However, there's no way to do that as of now.
I have to manually define each notification template only for changing the project names which is quite time taking.
For example my current notification template is below:
```
{{ define "title_success" -}}
✅ Successfully ran backup for Nextcloud {{ .Config.BackupStopContainerLabel }}
{{- end }}

{{ define "body_success" -}}
▶️ Start time: {{ .Stats.StartTime | formatTime }}
⏹️ End time: {{ .Stats.EndTime | formatTime }}
⌛ Took time: {{ .Stats.TookTime }}
🔐 Locked time: {{ .Stats.LockedTime }}
🛑 Stopped containers: {{ .Stats.Containers.Stopped }}/{{ .Stats.Containers.All }} ({{ .Stats.Containers.StopErrors }} errors)
📛 Backup name: {{ .Stats.BackupFile.Name }}
⚖️ Backup size: {{ .Stats.BackupFile.Size | formatBytesBin }} / {{ .Stats.BackupFile.Size | formatBytesDec }}
🗑️ Pruned backups: {{ .Stats.Storages.Local.Pruned }}/{{ .Stats.Storages.Local.Total }} ({{ .Stats.Storages.Local.PruneErrors }} errors)

{{- end }}
```
And I want that we should be able to retrieve the project name via environment variables like this:
```
{{ define "title_success" -}}
✅ Successfully ran backup for ${COMPOSE_PROJECT_NAME} {{ .Config.BackupStopContainerLabel }}
{{- end }}

{{ define "body_success" -}}
▶️ Start time: {{ .Stats.StartTime | formatTime }}
⏹️ End time: {{ .Stats.EndTime | formatTime }}
⌛ Took time: {{ .Stats.TookTime }}
🔐 Locked time: {{ .Stats.LockedTime }}
🛑 Stopped containers: {{ .Stats.Containers.Stopped }}/{{ .Stats.Containers.All }} ({{ .Stats.Containers.StopErrors }} errors)
📛 Backup name: {{ .Stats.BackupFile.Name }}
⚖️ Backup size: {{ .Stats.BackupFile.Size | formatBytesBin }} / {{ .Stats.BackupFile.Size | formatBytesDec }}
🗑️ Pruned backups: {{ .Stats.Storages.Local.Pruned }}/{{ .Stats.Storages.Local.Total }} ({{ .Stats.Storages.Local.PruneErrors }} errors)

{{- end }}

```
* **What is the expected behavior?**
There should be a way by which we can get/retrieve the name of the project/containers automatically in a notification template via environment variables.
* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  Latest tag: (2.18.0)
  - Image version: (2.18.0 (Latest)
  - Docker version: (Latest)
  - docker-compose version: (Latest)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by m90** [comment]
It should be possible to add a `TemplateFunc` that allows reading from the set environment variables in the templates here: https://github.com/offen/docker-volume-backup/blob/c2a8cc92fcfc05e974df4656f024161cdd464c40/cmd/backup/notifications.go#L75-L85

and then you'd have a template function to use like this

```
{{ (env "COMPOSE_PROJECT_NAME") }}
```

Right now I can't think of any security related problems that might bring, so if anyone wants to add this feature I'm happy to help with getting this merged.

**Comment by akash07k** [comment]
Ok, so will I have to modify the sources for that as it is not yet 
available in latest image?

**Comment by m90** [comment]
In case you want to open a PR containing this feature I can definitely merge and release it as soon as it's ready to go.

Else I might add this to one of the upcoming releases I'll be doing but I cannot tell you when exactly that will happen.

**Comment by akash07k** [comment]
Ok, that really sounds good.

I'll try to provide a PR soon probably on weekend since I'll have to 
unlock the bootloader of my phone tomorrow and will build a custom rom 
myself.

**Comment by akash07k** [comment]
Wonderful! Thanks a lot bro, really appreciated.

I'll try it now.

**Comment by m90** [comment]
The release is still being built, so if you wait another 30 minutes, that'd be helpful. Version will be `v2.19.0`.

**Comment by akash07k** [comment]
Yup, got it now, thanks bro! :-)
