### ISSUE TITLE
Insufficient permissions to access this file

### ISSUE THREAD

**Issue by mazz** [offen/docker-volume-backup#12]
Hi when I run 

`docker exec <container-id> backup` (I haven't tried a cron backup yet) I see:

```
[INFO] Uploading backup to remote storage

Will upload to bucket "secret-bucket-name".
`offen-db-2021-08-19T04-02-01.tar.gz` -> `backup-target/secret-bucket-name/offen-db-2021-08-19T04-02-01.tar.gz`
mc: <ERROR> Failed to copy `offen-db-2021-08-19T04-02-01.tar.gz`. Insufficient permissions to access this file `https://s3.amazonaws.com/secret-bucket-name/offen-db-2021-08-19T04-02-01.tar.gz`
Total: 0 B, Transferred: 1.28 KiB, Speed: 10.33 KiB/s
Upload finished.
```

I am connecting to Amazon S3 with the root keys, so I presume I am connecting with bucket owner permissions yet I get that error. 

The bucket is set to "Objects can be public" (The bucket is not public but anyone with appropriate permissions can grant public access to objects).

Any suggestions?

**Comment by m90** [comment]
This looks much like a permissions issue with your bucket / AWS credentials so it's very hard to debug from my end.

Just an idea: could it be that there's a typo in the actual bucket name you are using?

**Comment by mazz** [comment]
@m90 thanks for the feedback. I got filebase.com S3 backups working in https://github.com/offen/docker-volume-backup/issues/13 so I'll just close this rather than spin my wheels.
