### ISSUE TITLE
Clarification on backing up multiple compose files

### ISSUE THREAD

**Issue by aderouineau** [offen/docker-volume-backup#125]
Does this tool scan *all* containers hosted on the Docker instance regardless of the compose-file, or will it limit itself to the compose file in which it's defined?

I think it would be nice to clarify this in the README, so a user knows whether a dedicated compose file can be created to back-up the entire Docker host.

**Comment by m90** [comment]
> Does this tool scan all containers hosted on the Docker instance regardless of the compose-file

Yes. This image is not limited to be used in the context of docker-compose (which is nothing but a declarative way of handling multiple containers). The README also shows how to use it outside of the compose context using plain `docker` commands. The examples being in compose format is just a very convenient way of demonstrating concepts and features, however there's nothing you couldn't do using plain `docker`.

That being said, if you feel this could be improved (I might be way too deep in the topic), I am happy to merge PRs that clarify up on this. Thanks.
