### ISSUE TITLE
Incremental backups

### ISSUE THREAD

**Issue by aderouineau** [offen/docker-volume-backup#126]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* **What is the current behavior?**

Based on the documentation, it seems to do a full backup into an archive.

* **What is the expected behavior?**

Allow for an incremental back-up strategy. For example:
* Hourly incremental and daily full
* Daily incremental and weekly full
* Hourly incremental, daily incremental (from previous day, or aggregations of hourly within the day), and weekly full

* **What is the motivation / use case for changing the behavior?**

Reduce storage space requirements on backup targets, and therefore operational costs.

**Comment by aderouineau** [comment]
For example, I currently have bind mounts to a /data folder on the host and use an rclone container to transfer everything to Backblaze B2 with versioning enabled. I wonder how I could reach that level of optimal backup (bucket + versioning) with this tool.

**Comment by m90** [comment]
Incremental backups are out of scope for this image (or at least version 2) as it would blow up complexity a whole lot (supporting it for all of the different storage backends).

This might change if v3 (which is not planned right now) might switch to `rclone` (#109) or something similar. I have no idea if and how this is ever going to happen.

As for having different retention schedules for the same source, this is documented here: https://github.com/offen/docker-volume-backup#define-different-retention-schedules
