### ISSUE TITLE
Notifications Can't Handle Forward Slash In Credentials Field

### ISSUE THREAD

**Issue by ChuckMac** [offen/docker-volume-backup#128]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
If the SMTP username / password contains a forward slash ("/") then it does parse the URL properly.

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**
* 
`NOTIFICATION_URLS:` smtp://TEST:TEST/PASS@SERVER.COM:465/?fromAddress=test@test.com&toAddresses=test@example.com`
panic: newScript: error creating sender: error initializing router services: parse "smtp://TEST:TEST/PASS@SERVER.COM:465/?fromAddress=test@test.com&toAddresses=test@example.com": invalid port ":TEST" after host

`NOTIFICATION_URLS:` smtp://TEST:TEST\/PASS@SERVER.COM:465/?fromAddress=test@test.com&toAddresses=test@example.com`
panic: newScript: error creating sender: error initializing router services: parse "smtp://TEST:TEST\\/PASS@SERVER.COM:465/?fromAddress=test@test.com&toAddresses=test@example.com": invalid port ":TEST\\" after host

* **What is the expected behavior?**
Breaking special characters in the fields should be able to be escaped.

* **What is the motivation / use case for changing the behavior?**
AWS IAM gives you the credentials and does not allow them to be set.  They seem to really like giving a forward slash in the password - once I realized this was going to be problematic I had to regenerate them 5x before I got one without it.

* **Please tell us about your environment:**
  
  - Image version: v2.20.0
  - Docker version: 20.10.17
  - docker-compose version: 2.6.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by m90** [comment]
You need to URL encode the values in case they contain special characters https://github.com/offen/docker-volume-backup#use-special-characters-in-notification-urls
