### ISSUE TITLE
BACKUP_FROM_SNAPSHOT 2.15 to 2.20

### ISSUE THREAD

**Issue by zN3utr4l** [offen/docker-volume-backup#131]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

I decided to update by modifying everything so that **BACKUP_FROM_SNAPSHOT** continued to work, I followed everything as written in the READ.ME but I don't really understand what this error comes from.

This is my compose, with the backup image and my app to backup, I state that I have another compose that creates another volume to back up, I am also attaching this below

- 1
![image](https://user-images.githubusercontent.com/73225008/178982064-64f67048-a09d-458d-895f-1d053c46a4f2.png)
![image](https://user-images.githubusercontent.com/73225008/178982501-a42ec4a2-a31d-45fb-af58-1263aa56c2db.png)

- 2
![image](https://user-images.githubusercontent.com/73225008/178982715-c393ebdd-c3ca-47a2-a21e-799580145e54.png)
![image](https://user-images.githubusercontent.com/73225008/178982644-d25cccb2-24be-41c6-84df-8457c47e5227.png)

In boot order, the compose is started first in section 2 for this in the other compose the backup volume is marked external, as it has already been created

**Problem**
Either if I start the container with the scheduler or if I call the backup process the error message is this.
![image](https://user-images.githubusercontent.com/73225008/178983050-20a9379f-792f-4dd8-aaf3-a4bee826c0c8.png)
![image](https://user-images.githubusercontent.com/73225008/178983089-183becd1-517b-43e4-bded-06fc2f796773.png)

  
  - Image version: 2.20
  - Docker version: latest
  - docker-compose version: 3.9

**Comment by m90** [comment]
I'm not entirely sure why this is happening as your configuration looks ok on first glance (text format would be great btw so people can copy/paste), so right now I don't have an idea why it gets the ordering wrong in your case.

I also tried reproducing this in the test case for running commands and couldn't, even when I added more than one container that is running commands, which makes me think it's something else that is specific to your setup and/or configuration. Would you mind sharing the entirety of your compose file so we can maybe spot what's going on?

**Comment by zN3utr4l** [comment]
[test backup.zip](https://github.com/offen/docker-volume-backup/files/9112086/test.backup.zip)

**Comment by m90** [comment]
Would you mind posting the contents here for better visibility or do they contain anything sensitive?

**Comment by zN3utr4l** [comment]
I made you the whole structure of how I have it here locally, with the various configurations etc., I can't put it directly here

**Comment by zN3utr4l** [comment]
I made a mistake in compose, I edited the zip for you

**Comment by zN3utr4l** [comment]
-Root Folder
![image](https://user-images.githubusercontent.com/73225008/178994765-6378aa51-7fef-489a-a675-35cbe855aba6.png)

[commands.txt](https://github.com/offen/docker-volume-backup/files/9112217/commands.txt)
[docker-compose1.yml.txt](https://github.com/offen/docker-volume-backup/files/9112218/docker-compose1.yml.txt)
[docker-compose2.yml.txt](https://github.com/offen/docker-volume-backup/files/9112219/docker-compose2.yml.txt)
[mongo.env.txt](https://github.com/offen/docker-volume-backup/files/9112220/mongo.env.txt)
[timescale.env.txt](https://github.com/offen/docker-volume-backup/files/9112221/timescale.env.txt)

- Mongo Folder
![image](https://user-images.githubusercontent.com/73225008/178995003-7e53ce33-2ba7-43eb-9a88-233f69695442.png)

[Dockerfile.txt](https://github.com/offen/docker-volume-backup/files/9112227/Dockerfile.txt)
[mongod.conf.txt](https://github.com/offen/docker-volume-backup/files/9112228/mongod.conf.txt)

- Timescale Folder
![image](https://user-images.githubusercontent.com/73225008/178995123-93f079ad-ccfc-47e8-b516-937a401f1c38.png)
[Dockerfile.txt](https://github.com/offen/docker-volume-backup/files/9112232/Dockerfile.txt)
[postgresql.conf.txt](https://github.com/offen/docker-volume-backup/files/9112233/postgresql.conf.txt)

**Comment by zN3utr4l** [comment]
Always the same problem

![image](https://user-images.githubusercontent.com/73225008/178996424-c373c7cd-3f17-4fd6-8568-84741943b3bb.png)

**Comment by m90** [comment]
I can't run your example as it references a local hard drive of yours.

In any case I have no good idea why this is happening to you as the configuration looks correct, however I cannot reproduce this behavior in any case, nor do I have any idea what might make the steps run in an incorrect order. Feel free to share anything you attempt here so I can give feedback (in case I have any), but right now this is all the help I can give you.

**Comment by m90** [comment]
I don't know either. You could exec into the container and see what `/tmp/backup` contains, but that's just a guess.

**Comment by m90** [comment]
Do you mount the Docker socket into the backup container? In case no, the backup command cannot interact with other containers on the host. See: https://github.com/offen/docker-volume-backup#recurring-backups-in-a-compose-setup
