### ISSUE TITLE
pruneBackups: error looking up candidates from remote storage

### ISSUE THREAD

**Issue by ghost** [offen/docker-volume-backup#137]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Hello,

I'm looking for rotating and pruning my backups, since they are becoming quite big.
So here my .env config :

```bash
BACKUP_RETENTION_DAYS=7
BACKUP_PRUNING_LEEWAY=1h
BACKUP_PRUNING_PREFIX=backup-
```

But I get this : 

```log
time="2022-07-22T09:14:59+02:00" level=info msg="Stopping 1 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 18 running container(s)."
time="2022-07-22T09:15:16+02:00" level=info msg="Created backup of `/backup` at `/tmp/backup-2022-07-22T09-14-58.tar.gz`."
time="2022-07-22T09:15:17+02:00" level=info msg="Restarted 1 container(s) and the matching service(s)."
time="2022-07-22T09:15:20+02:00" level=info msg="Encrypted backup using given passphrase, saving as `/tmp/backup-2022-07-22T09-14-58.tar.gz.gpg`."
time="2022-07-22T09:15:22+02:00" level=info msg="Uploaded a copy of backup `/tmp/backup-2022-07-22T09-14-58.tar.gz.gpg` to bucket `........`."
time="2022-07-22T09:15:23+02:00" level=error msg="Fatal error running backup: pruneBackups: error looking up candidates from remote storage: The specified key does not exist."
time="2022-07-22T09:15:23+02:00" level=info msg="Removed tar file `/tmp/backup-2022-07-22T09-14-58.tar.gz`."
time="2022-07-22T09:15:23+02:00" level=info msg="Removed GPG file `/tmp/backup-2022-07-22T09-14-58.tar.gz.gpg`."
```

But, at the end, the tar.gz.gpg is uploaded.
I would like to know if that error lets DVB uploading in the bucket ?
Or It's just a warning because my backups are younger than 7 days?

And I have another question, 
So, my stacks are divided by docker-compose.yml : one for specific goal.
Each has a DVB for dedicated volumes.

But when I'm executing this command (inside a specific one) : 

```bash
docker compose exec backup backup
```
I can see logs related to another containers and stacks with the labels : archive-pre.
It is like an unnecessary operation, I don't know if I explain myself well :p !

Thank you for your work ! I really appreciate it !

Erwan

**Comment by rwanito** [comment]
Hello,

It looks like my S3 server is the problem.
I'll debug after the last PR I saw because maybe It looks easier.

After, I will give you a PR to adjust some options or debug messages!

Thank you!
