### ISSUE TITLE
SSH error when backing up to ssh

### ISSUE THREAD

**Issue by jsloane** [offen/docker-volume-backup#149]
**Describe the bug**
SSH error when backing up to ssh.

> panic: newScript: error creating ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
> 
> goroutine 1 [running]:
main.main()
        /app/cmd/backup/main.go:13 +0x4a8

I verified the SSH keys worked when connecting from the host machine.

**To Reproduce**
1. Generate SSH keys using either `ssh-keygen` or `ssh-keygen -t ed25519` on Ubuntu 22.04.1 LTS
2. Run backup using SSH keys and the backup will fail

**Expected behavior**

**Desktop (please complete the following information):**
 - Image Version: offen/docker-volume-backup:latest
 - Docker Version: Docker version 20.10.17, build 100c701
 - Docker Compose Version (if applicable): docker-compose version 1.29.2, build unknown

**Additional context**
According to this, it could be caused by an outdated go.mod file: https://stackoverflow.com/questions/72702629/golang-ssh-client-error-unable-to-authenticate-attempted-methods-none-publick

**Comment by m90** [comment]
> attempted methods [none]

This (listing `none` only) sounds as if your configuration does not pick up keys correctly. How do you mount the keys into the container and what `SSH_*` configuration options are you using?

**Comment by jsloane** [comment]
I generated the keys on the host OS and mount the file with volume:
            - /home/remote-backup/.ssh/id_ed25519:/root/.ssh/id

I also tried with (with root ownership):
            - /data/remote-backup-id_ed25519:/root/.ssh/id

The SSH_ configuration is:

> SSH_HOST_NAME: 10.100.105.1
SSH_PORT: 22
SSH_USER: remote-backup
SSH_REMOTE_PATH: /data/remote-backup-volumes

**Comment by m90** [comment]
Seems you uncovered a typo in the example here: https://github.com/offen/docker-volume-backup#backing-up-to-ssh

The default key location is `/root/.ssh/id_rsa` (this is also documented in the configuration reference). If you want to use a non-default value (your example strips the `_rsa` suffix), you need to set `SSH_IDENTITY_FILE`.

**Comment by m90** [comment]
Fixed the example here https://github.com/offen/docker-volume-backup/commit/231611189295ce87f6051a0cd7498b54093d0ac3

**Comment by m90** [comment]
Closing this as it seems to be completed.
