### ISSUE TITLE
Fatal error running backup: compress: error walking filesystem tree: lstat /backup: no such file or directory

### ISSUE THREAD

**Issue by davidwuest** [offen/docker-volume-backup#150]
Getting the following error and can't make sense of it:

time="2022-08-30T18:18:55Z" level=error msg="Fatal error running backup: compress: error walking filesystem tree: lstat /backup: no such file or directory"
time="2022-08-30T18:18:55Z" level=info msg="Removed tar file `/tmp/backup-2022-08-30T18-18-55.tar.gz`."

Dictionary is there and even if deleted is back with manual backup executed. 

   volumes:
      - mssql_data:/var/opt/mssql:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/USER/sql/backups:/archive

**Comment by m90** [comment]
For the container based on `offen/docker-volume-backup`, you need to mount your `mssql_data` volume to a path under `/backup`, not the location your database server expects it to be mounted. Alternatively you can set `BACKUP_SOURCES`  to a non-default location.

E.g. your volume definition would become:

```yml
volumes:
  - mssql_data:/backup/mssql_data
  - /var/run/docker.sock:/var/run/docker.sock:ro
  - /home/USER/sql/backups:/archive
```

See the example in the README https://github.com/offen/docker-volume-backup#recurring-backups-in-a-compose-setup and the configuration reference: https://github.com/offen/docker-volume-backup#configuration-reference

**Comment by davidwuest** [comment]
Thanks @m90
