### ISSUE TITLE
Support for Cron Job Monitoring Tools such as healthchecks.io

### ISSUE THREAD

**Issue by engineervix** [offen/docker-volume-backup#159]
**What are you trying to do?**
I would like to use a service such as healthchecks.io to monitor my backup cron jobs, but I do not know if this is possible out the box, or whether some additional customisation is required.

**What is your current configuration?**
Here's a configuration I'm using: https://github.com/engineervix/taiga-docker/blob/stable/docker-compose.yml

**Log output**
N/A

**Additional context**
I know from the docs that there's already a feature to send out email notifications on failed backup runs. However, I understand this to be failures in the backup process itself. What I'd like to monitor is the cron job, so that if, for some reason (power disruption, etc.), the cron job isn't triggered, then I get an alert.

**Comment by m90** [comment]
Looking at this: https://healthchecks.io/docs/monitoring_cron_jobs/ I think you could get away with running the ping in a "command hook": https://github.com/offen/docker-volume-backup#run-custom-commands-during-the-backup-lifecycle once the backup run has finished (or before it starts?). `wget` is installed in the image.

**Comment by engineervix** [comment]
Thanks @m90 I'll check it out later and post an update here

**Comment by engineervix** [comment]
Hi @m90 thanks once again for your help! I managed to have it working by defining a **pre**-command that runs `wget ${HEALTHCHECKS_PING_URL} -O /dev/null` inside the `docker-volume-backup` container itself -- in the `archive` phase of the backup lifecyle.

This can be seen in:

https://github.com/engineervix/taiga-docker/blob/e91146bec95e7752afb8906e96b23e055da7ad5d/docker-compose.yml#L168-L172.

Closing this as it's resolved 👍

**Comment by m90** [comment]
Cool, thanks for sharing your setup :tophat: I'm sure others will find this very helpful.

**Comment by federicotravaini** [comment]
It would be very helpful to include this solution in the documentation (just because I've been looking for a solution like this myself)

**Comment by m90** [comment]
@federicotravaini Mind opening a PR that adds it? I'm more than happy to merge it
