### ISSUE TITLE
Best way to restore volume: swap-in volume for existing image/container?

### ISSUE THREAD

**Issue by mazz** [offen/docker-volume-backup#16]
from your how-to(https://dev.to/hendr_ik/automate-backing-up-your-docker-volumes-3gdk?signin=true): 

> The volume is now ready to use in other containers. Alternatively, you can use a one-off volume created beforehand.

so I managed to cp the restore file to the `offen_data` volume:

`docker run -d --name backup_restore -v offen_data:/backup_restore alpine`
`docker cp ~/Downloads/backup/faithful-word-database-backup backup_restore:/backup_restore`

which copies the backup data into the `offen_data` volume.

I have an existing volume attached to a running container that I want to replace with `offen_data`:

`faithful-word_database-storage`

How do I swap-in the restored volume to the existing container?

I tried:
`docker-compose down`
`docker volume rm faithful-word_database-storage`
`docker volume create --name faithful-word_database-storage`
`docker run --rm -it -v offen_data:/from -v faithful-word_database-storage:/to alpine ash -c "cd /from ; cp -av . /to"`

but when I do `docker-compose up` the running container is not associated with the new volume containing restored data.

How do I associate the new volume with the image/container? Or perhaps this is not the "right" way to do this.

**Comment by m90** [comment]
Why don't you always use the `faithful-word_database-storage` volume?

E.g.:

- you take down the application container
- you keep the volume
- you mount the volume into a temporary container
- you copy over the files and potentially do cleanup using the temporary container
- you stop and remove the temporary container
- you bring the application container back up

**Comment by mazz** [comment]
Got it! Thanks. Here's what got me there:

> you take down the application container
`docker-compose down`
> you mount the volume into a temporary container
docker run -d --name backup_restore -v markably-media-feed_database-storage:/backup_restore alpine
> you copy over the files and potentially do cleanup using the temporary container
cd ~/Downloads/backup-2/faithful-word-database-backup
docker cp . backup_restore:/backup_restore
> you stop and remove the temporary container
docker stop backup_restore && docker rm backup_restore
> you bring the application container back up
docker-compose up

Some other useful docker commands:

bash access running postgres docker container instance: `docker exec -ti markably-media-feed_postgres_1 bash`
inspect volume sizes: `docker system df -v`
ls: `docker run --rm -v markably-media-feed_database-storage:/data/ ubuntu ls -la /data`
delete volumes files: `docker run --rm -v markably-media-feed_database-storage:/data/ ubuntu /bin/sh -c "rm -rf /data/*"`
