### ISSUE TITLE
Question | What order does the actions happen?

### ISSUE THREAD

**Issue by michaelkr1** [offen/docker-volume-backup#168]
Hey there. I'm looking into a volume backup solution and came across this. I'd just like to know whether all the containers are stopped THEN the backup of the volume occurs or does it stop the container, then backup that containers volume, starts the container and moves onto the next one?

Reason I ask is because all the volumes for all the containers I want to backup are nested in one directory (EG. /mnt/docker/) and I'm wondering whether it will work (as in shutdown all the containers and backup the full root dir) if I just include the that root directory in the backup container.

Hope this makes sense.

Cheers,

**Comment by m90** [comment]
By default, all running containers will be stopped, and then restarted when the backup has finished.

If you need more fine grained control over that behavior, you can use the `BACKUP_STOP_CONTAINER_LABEL`  feature: https://github.com/offen/docker-volume-backup#stop-containers-during-backup
