### ISSUE TITLE
Corrupted Backup

### ISSUE THREAD

**Issue by patrickap** [offen/docker-volume-backup#175]
**Describe the bug**
The creation of the archive seems to be broken. According to the logs the backup was created successfully. When I try to open it an error occurs.

**Expected behavior**
I should be able to open the archive.

**Desktop**
 - Image Version: v2.22.2
 - Docker Version: 20.10.17
 - Docker Compose Version: 3.7

**Additional context**
<img width="581" alt="Bildschirm­foto 2023-01-01 um 16 04 08" src="https://user-images.githubusercontent.com/67900846/210175282-12722779-6267-4e0c-9b05-124bd3c4568a.png">

**Comment by m90** [comment]
This has to be specific to your setup (tests are in place to make sure it's working in default use cases). Could you provide further information on:

- what are the expected contents of your archive
- how do you try to extract contents
- your configuration

**Comment by patrickap** [comment]
Thanks for your feedback. I have tried several tools. On Linux and MacOS. The following command fails but should work: `tar -xzvf backup.tar.gz`.

My configuration looks like this:
```yml
BACKUP_CRON_EXPRESSION="0 3 * *"
BACKUP_RETENTION_DAYS="7"
BACKUP_FILENAME="%Y-%m-%d_%H.%M.%S.tar.gz"
BACKUP_LATEST_SYMLINK="main.tar.gz"
```

In `backup.tar.gz` there are mainly audio files, images, ...
It fails at a larger ZIP file (about 30GB). Have already copied and unpacked it manually for testing. No errors. Should I split the large ZIP file?

**Comment by m90** [comment]
That 30GB Zip file sounds like a likely culprit. To get an idea about where things go wrong, are you able to tar and untar that file using plain command line `tar`?

**Comment by patrickap** [comment]
It was actually the large ZIP file. Although I could unpack it the transfer was somehow broken. I have now split it into small 2GB parts. Now everything works fine. Thanks for the hint and this awesome piece of software!
