### ISSUE TITLE
Problems with multiple schedules

### ISSUE THREAD

**Issue by patrickap** [offen/docker-volume-backup#176]
I have a requirement to create daily and weekly backups. I only want to encrypt the weekly backups and upload them to the cloud via Rclone. I have seen that there is the possibility to define multiple schedules and use lifecycle hooks. How can I make sure that the hook is only triggered for the weekly backups? Currently this runs every time. Even when instantiating two separate containers, the command is triggered on every backup.

**Comment by m90** [comment]
I'm not entirely sure if this covers your use case, but if you only need to run the lifecycle hooks for the weekly backup, you should be able to define an `EXEC_LABEL` here and use one container per schedule. Have you tried doing this already?

**Comment by patrickap** [comment]
Somehow missed that section in the readme. Works fine. Thanks a lot!
