### ISSUE TITLE
Cannot backup containers under rootless docker installation

### ISSUE THREAD

**Issue by gaatorre** [offen/docker-volume-backup#189]
**Describe the bug**

When using a rootless docker installation, there does not exist mechanism to set the user and group id of the container. As a result, the container runs into a "Permission Denied" error as the container is running as root. Setting `UID` and `GID` in the environment file does not set the id values nor does `user: 1000:1000` in a docker-compose.yaml file.

**To Reproduce**
1. Have a docker rootless installation.
2. Bind mount the user's docker.sock.

**Expected behavior**

executing `$ id` inside the container should return uid=1000, gid=1000 if set to those values in the environment file.

**Version (please complete the following information):**
 - Image Version: 2.25.1
 - Docker Version: 20.10.22
 - Docker Compose Version (if applicable): 2.14.1

**Additional context**

**Comment by gaatorre** [comment]
I am an idiot. I was bind mounting `/run/usr/1000/docker.sock` instead of `/run/user/1000/docker.sock`

**Comment by m90** [comment]
This might be worth adding to the README, thanks for pointing it out.
