### ISSUE TITLE
Notification templates

### ISSUE THREAD

**Issue by hugomickael** [offen/docker-volume-backup#193]
Hi, 
I would like to have some help to use the notification templates, because this folder /etc/dockervolumebackup doesn't exist, or I don't know what does it mean. I need to create it on the backup container?
Regards.

**Comment by m90** [comment]
> I need to create it on the backup container?

You do implictly create the directory when you mount your template file (or directory of templates) into the container:

```yml
# in your backup service definition
volumes:
  # if the target path does not exist, docker will create the missing directories for you
  - ./your-template.tmpl:/etc/dockervolumebackup/notifications.d/your-template.tmpl
```

**Comment by hugomickael** [comment]
Ok, understood. Thanks for your help.
