### ISSUE TITLE
High RAM memory usage on idle and runtime

### ISSUE THREAD

**Issue by MarkoArsic** [offen/docker-volume-backup#198]
**Bug description**
Hello, i'm backing up few containers, total backup size (.gz) is around 17GB, problem is very high RAM memory usage, both when container is running backup and when container is in idle state.
Idle is 9-15GB
Running backup 37-39GB
From my point of view this is very high, what do you think?

**Version:**
 - Image Version:  e.g. v2.7.2 
 - Docker Version:  e.g. 20.10.12 
 - Docker Compose Version:  v2.1.1 
![image](https://user-images.githubusercontent.com/15787932/225601787-44e10324-63ba-4009-bcf9-68e267558739.png)

Thank you!

**Comment by m90** [comment]
Are you using Docker in swarm mode? This reminds me of https://github.com/offen/docker-volume-backup/issues/9

If that is not the case, what's your target backend? Maybe there is a leak in the implementation there.

**Comment by MarkoArsic** [comment]
No, i'm not using swarm mode, just a single instance of backup and all others containers with docker-compose.
What do you mean with "target backend"?

here is the example of container definition
backup:
        restart: always
        profiles: ["backup"] 
        image: offen/docker-volume-backup:v2.7.2
        hostname: dzgz
        environment:
            - BACKUP_FILENAME=backup-%Y-%m-%dT%H-%M-%S.tar.gz
            - BACKUP_LATEST_SYMLINK=backup.latest.tar.gz.gpg
            - BACKUP_RETENTION_DAYS=2
            - BACKUP_PRUNING_LEEWAY=5m
            - BACKUP_PRUNING_PREFIX=backup-
            - BACKUP_CRON_EXPRESSION=0 19 * * 1-5
            - NOTIFICATION_URLS=smtp://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            
            - NOTIFICATION_LEVEL=info
        volumes:
            - xxxxxxxxx
            - xxxxxxxxx
            - xxxxxxxxx
            - xxxxxxxxx
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./backups:/archive  
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

**Comment by m90** [comment]
Also, when debugging this, it might be helpful if you could upgrade to the latest version, `v2.25.1` so we can make sure you're not being bitten by sth that has changed in the last year anyways.

**Comment by MarkoArsic** [comment]
Thanks for your responsiveness,
when i use hard mem limit, it slows down very much. 
1GB Ram and backup will last 5 hours .. 
Eventually , backup will be done but very slow.
I will try with the update.
What is OOM?
I do not see any unusual  logs in backup container...

**Comment by m90** [comment]
For such a slow backup run, could you post the log output here? I'd be interested if this is archive creation or copying being the bottleneck? I'd suspect the latter, but I don't know. Also: are you backing up to a local disk or to a network file system?

"OOM killed" means Docker exits a container forcefully as it's out of memory.

**Comment by MarkoArsic** [comment]
This is the log from backup container that have no mem limits, it's log is in first post  of this thread.

![image](https://user-images.githubusercontent.com/15787932/226321353-dc0fbd86-c111-49aa-b671-7ff65a0e20a6.png)

I think that everything is fine, no errors, no "OOM Killed"..

Below is the backup mem usage in last 7 days, peaks are at 19h when backup is performed.
![image](https://user-images.githubusercontent.com/15787932/226322358-06fd452a-2429-4435-8648-da762402ff93.png)

**Comment by MarkoArsic** [comment]
Forgot to answer > Local disk is backup location (enterprise grade SSD).


Chart below is from the Prod server i cant change antyhing right now untill im 100% sure i got the solution, lets move to Test server, where situation is a bit better, there is 20% less data, there are no errors, whole envirionment is exacly the same as Prod server.

![image](https://user-images.githubusercontent.com/15787932/226378519-eb6e3d51-c7dc-43f7-8e4c-6a45ffe9c1e9.png)


All peaks on the left are Image Version:  v2.7.2, last one(on the right) is v2.25.1 (latest), there is  no mem_limit and everything is the same as the old image regarding the mem consumtion. The idle ram consumption is much less than on the prod server but still high when container does nothing.

What i'm actually worried about is the amount of memory that container consumes while not doing anything and it is around 4GB on Test instance and 14-15GB on Prod instance, i have no problem when container consumes 30-40GB of RAM while manipulating with 15-20GB of backups.

Manual backup logs (after image update)
![image](https://user-images.githubusercontent.com/15787932/226377871-f75b013e-e14c-4c01-80f9-444a65a4183f.png)

In next post i will do a mem limit on Test instance..

**Comment by MarkoArsic** [comment]
.... this is with 3GB mem_limit (16h, right peak)
![image](https://user-images.githubusercontent.com/15787932/226398636-41742582-d05f-420e-890c-d49d11815f5b.png)
It is very strange, i sated 3GB mem_limit but it went to 9GB which is 10GB less then before mem_limit (right peak), and it did a backup in 40 minutes, which is exactly the same as without mem_limit>
![image](https://user-images.githubusercontent.com/15787932/226399683-e564e109-a586-44b0-8e5b-b12ba9f3ba8e.png)

**Comment by m90** [comment]
I start wondering if your monitoring is reporting the correct values. If you limit memory to 3GB, but the graph shows over 18GB of usage, this somehow doesn't add up.

Also: when idling, there is nothing but `crond` running inside of the container. I really don't think this can consume more than a few megabytes, and all instances I have deployed myself also don't use more than 20MB of RAM when idling.

Maybe you are indeed seeing what's been described here: https://github.com/offen/docker-volume-backup/issues/9#issuecomment-881613931 ?

**Comment by m90** [comment]
Closing this as there doesn't seem to be any actionable output. If you find out more about this, feel free to reopen.
