### ISSUE TITLE
/bin/ash: entrypoint.sh: not found

### ISSUE THREAD

**Issue by lucas-im** [offen/docker-volume-backup#200]
**Describe the bug**

**To Reproduce**
1. ...Seup cron schedule
2. ...Wait for it to trigger
3. .../bin/ash: entrypoint.sh: not found

**Expected behavior**

**Version (please complete the following information):**
 - Image Version: latest
 - Docker Version: latest
 - Docker Compose Version (if applicable): latest

**Additional context**
manual backup(docker exec -it backup /bin/ash then backup) works perfectly
<img width="435" alt="Screenshot 2023-03-27 at 10 29 48 AM" src="https://user-images.githubusercontent.com/72141676/227819799-1a5a4e3c-fbad-4494-ba15-4def5b5e8548.png">

**Comment by lucas-im** [comment]
```
BACKUP_CRON_EXPRESSION="0 18 */2 * * *"

BACKUP_FILENAME="backup-%Y-%m-%dT%H-%M-%S.tar.gz"
BACKUP_FILENAME_EXPAND="true"

BACKUP_EXCLUDE_REGEXP="\.log$"

AWS_S3_BUCKET_NAME=blah

AWS_ACCESS_KEY_ID=blah
AWS_SECRET_ACCESS_KEY=blah

BACKUP_RETENTION_DAYS="7"
BACKUP_PRUNING_PREFIX="backup-"

NOTIFICATION_URLS=blah
NOTIFICATION_LEVEL="error"
```

**Comment by m90** [comment]
You've got a trailing `*` in your cron expression, so crond tries to call `*`, which is not found.

A cron expression consist of 5 elements, yours has 6.
