### ISSUE TITLE
Backing up two container volumes using SSH (with SSH Key, not password) not working

### ISSUE THREAD

**Issue by muralidharanram** [offen/docker-volume-backup#201]
**What are you trying to do?**
I'm trying to do a volume backup of two docker containers - container1, container2 using the docker run commands described in the configuration section.

For testing, I am triggering the backup manually using the `docker exec <container> backup` command.

**What is your current configuration?**
```
docker run --rm \
  -d -t \
  --name testing-backup \
  -e BACKUP_FILENAME=backup-%Y-%m-%dT%H-%M-%S.tar.gz \
  -e BACKUP_RETENTION_DAYS=30 \
  -e BACKUP_PRUNING_PREFIX="backup-" \
  -e NOTIFICATION_URLS=telegram://${TELEGRAM_TOKEN}@telegram?chats=${TELEGRAM_CHAT_ID} \
  -e NOTIFICATION_LEVEL=info \
  -e SSH_HOST_NAME="mydomain.com" \
  -e SSH_PORT=22 \
  -e SSH_REMOTE_PATH="/home/user/backup/" \
  -e SSH_USER="user" \
  -e SSH_IDENTITY_FILE="/home/user/appdata/backup/id_rsa" \
  -e SSH_IDENTITY_PASSPHRASE="" \
  -e BACKUP_ARCHIVE=/archive \
  -v /home/user/appdata/container1:/backup/container1:ro,z \
  -v /home/user/appdata/container2:/backup/container2:ro,z \
  -v /home/user/appdata/backup/archive:/archive:rw,Z \
  -v /var/run/docker.sock:/var/run/docker.sock:ro,z \
offen/docker-volume-backup:v2

# manually run the backup
docker exec testing-backup backup
```

**Log output**
```
$ docker exec testing-backup backup
panic: NewStorageBackend: Error creating ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

goroutine 1 [running]:
main.main()
	/app/cmd/backup/main.go:13 +0x4a0
```

**Additional context**
I've individually tested the following
1. the SSH keys (`ssh user@mydomain.com -i /home/user/appdata/backup/id_rsa` from the host works flawlessly after selecting "Yes" for adding the host fingerprint to the known_hosts list). This specific key doesn't have a passphrase, hence SSH_IDENTITY_PASSPHRASE="", if that means anything. Nevertheless the SSH connection gets established directly from the host.
2. Removed the ssh backup related env variables and rerun the test to make sure the local backup happens - It does, no issues here. This config is shown below

```
docker run --rm \
  -d -t \
  --name testing-backup \
  -e BACKUP_FILENAME=backup-%Y-%m-%dT%H-%M-%S.tar.gz \
  -e BACKUP_RETENTION_DAYS=30 \
  -e BACKUP_PRUNING_PREFIX="backup-" \
  -e NOTIFICATION_URLS=telegram://${TELEGRAM_TOKEN}@telegram?chats=${TELEGRAM_CHAT_ID} \
  -e NOTIFICATION_LEVEL=info \
  -e BACKUP_ARCHIVE=/archive \
  -v /home/user/appdata/container1:/backup/container1:ro,z \
  -v /home/user/appdata/container2:/backup/container2:ro,z \
  -v /home/user/appdata/backup/archive:/archive:rw,Z \
  -v /var/run/docker.sock:/var/run/docker.sock:ro,z \
offen/docker-volume-backup:v2

docker exec testing-backup backup
```

This makes me believe that the problem lies only with the SSH connection/backup.

I've managed to configure a external cron job that uses rsync to synchronize the .../archive/ directory to the remote host "mydomain.com". It works. Kinda. But any help to identify this issues with my configuration is greatly appreciated.

**Comment by m90** [comment]
Looking at the command you are trying to run, I can see that you do pass `SSH_IDENTITY_FILE="/home/user/appdata/backup/id_rsa"`, but then you don't mount the key into the container. In order for the container to be able to use the key, it must be able to read it:

https://github.com/offen/docker-volume-backup/blob/main/internal/storage/ssh/ssh.go#L48

Also see the last entry in the list of volumes here: https://github.com/offen/docker-volume-backup#backing-up-to-ssh

**Comment by muralidharanram** [comment]
Yes, that worked!. Thanks.

So, the `SSH_IDENTITY_FILE=` isn't a host path but a container path. Never thought of that.

**Comment by m90** [comment]
Luckily, there is no way for the container to read keys on the host system, so they need to be mounted explicitly:

```
# The private key path in container for SSH server
# Default value: /root/.ssh/id_rsa
# If file is mounted to /root/.ssh/id_rsa path it will be used. Non-RSA keys will
# also work.

# SSH_IDENTITY_FILE="/root/.ssh/id_rsa"
```
