### ISSUE TITLE
Add option to only prune local archive

### ISSUE THREAD

**Issue by esolitos** [offen/docker-volume-backup#207]
**Is your feature request related to a problem? Please describe.**

Currently it does not seem to be possible to only prune the "local" backups, which causes unwanted errors when using write-only backeds, for example S3 with the appropriate permissios.

This causes the logs to be filled with errors like:

> level=error msg="Fatal error running backup: pruneBackups: error pruning backups: [Access Denied, Access Denied, Access Denied, Access Denied, Access Denied]"

This is not good as the amount of "false positives" could make other more important errors go unnoticed due to "notification fatigue".

**Describe the solution you'd like**

I would like to be able to specify _which backends_ should be pruned, this could be achieved using a config option like `BACKUP_PRUNE_SKIP_BACKENDS=list` or by adding the option to each of the relevant backed.

Examples:
- `AWS_S3_SKIP_PRUNE` or `AWS_S3_WRITE_ONLY`
- `AZURE_STORAGE_SKIP_PRUNE` / `AZURE_STORAGE_WRITE_ONLY`
- and so on...

Ideally each backend should either implement a `ShouldPrune()` method to call [before the `Prune`](https://github.com/offen/docker-volume-backup/blob/46c6441d482094ca4be3d42c38c119f944d8f9fe/cmd/backup/script.go#L551) call, or the `Prune` itself should handle this.

**Describe alternatives you've considered**

- Run 2 instances: one performs the backups and another performs the prune (without access to the backend).
  This could work, however we need to perform the prune and the backups in very different schedules to prevent issues.
- Do not use this container for backups rotation.

**Additional context**

N/A

**Comment by m90** [comment]
This is now possible as of [v2.31.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.31.0)

**Comment by esolitos** [comment]
Amazing, thanks @MaxJa4 and @m90 !
