### ISSUE TITLE
hardcoded TaskTemplate.ForceUpdate value

### ISSUE THREAD

**Issue by tarybarna** [offen/docker-volume-backup#208]
**Describe the bug**
after successfully stopping the specified containers and saving the backup, swarm services are not being force updated due to the hardcoded `TaskTemplate.ForceUpdate` (always 1) which should be different across update calls to actually trigger the updates and therefore start the previously stopped containers

**To Reproduce**
1. configure a backup container to stop and then restart a container managed by a swarm service

**Expected behavior**
swarm services should be actually force updated during restarts so containers will restart

**Version (please complete the following information):**
 - Image Version: v2.26.1
 - Docker Version:  20.10.9

**Comment by m90** [comment]
I don't fully understand the scenario you are describing yet. Could you provide a compose file that I could use to reproduce the issue?

**Comment by m90** [comment]
This is fixed in [v2.26.2](https://github.com/offen/docker-volume-backup/releases/tag/v2.26.2)
