### ISSUE TITLE
Backup triggers others offen containers

### ISSUE THREAD

**Issue by erwanlpfr** [offen/docker-volume-backup#210]
Hello,

I have plenty of `docker-compose` files on my VM. 
They are running in single instance of Docker; no swarm or whatever.

So, on each `docker-compose` file, I provide a **offen** instance with `EXEC_LABEL=${NAME}`
And the linked ones are supplied by the label `exec-label...`.

When I run a backup, it shuts down the related extra container even if I was in another instance.
It looks like it reads external containers of this instance and ignores the `EXEC_LABEL` variable.

```bash
time="2023-04-27T20:20:56+02:00" level=info msg="Stopping 1 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 20 running container(s)."
```

How can I run, granulated, backups for only one `docker-compose`?

Thank you!

**Comment by m90** [comment]
> Stopping 1 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 20 running container(s).

This seems expected. Is it actually stopping more than the 1 container? Considering all containers run on the same host, no matter how many compose files you use, there's no easy way of preventing `docker-volume-backup`  from _looking_ at all containers on the host, however when using `EXEC_LABEL`  it should only stop the ones that are labeled accordingly. Are you sure it actually stops containers it shouldn't be stopping?

**Comment by m90** [comment]
It might also be worth noting that there is `EXEC_LABEL` which determines which containers are expected to run commands, and then there's `BACKUP_STOP_CONTAINER_LABEL` which determines which containers will be stopped: https://github.com/offen/docker-volume-backup#stop-containers-during-backup

**Comment by erwanlpfr** [comment]
> It might also be worth noting that there is `EXEC_LABEL` which determines which containers are expected to run commands, and then there's `BACKUP_STOP_CONTAINER_LABEL` which determines which containers will be stopped: https://github.com/offen/docker-volume-backup#stop-containers-during-backup


I confirm, this one does the job ! Thanks !
Another question, if it is necessary to open another issue, let me know.

```yaml
labels:
  - docker-volume-backup.exec-label=nextcloud-aio
  - docker-volume-backup.archive-pre-www-data=/bin/sh -c './occ maintenance:mode --on'
  - docker-volume-backup.copy-post-www-data=/bin/sh -c './occ maintenance:mode --off'
```

These commands seem to be ignored while running the backup, even if `EXEC_LABEL: nextcloud-aio` is provided.

**Comment by m90** [comment]
There's a trailing `www-data` in both labels, which means no command is recognized.

**Comment by erwanlpfr** [comment]
Sure ! I wanted to do something like this from : https://github.com/offen/docker-volume-backup#run-custom-commands-during-the-backup-lifecycle

>By default the backup command is executed by the root user. It is possible to specify a custom user in container labels with the format docker-volume-backup.[step]-[pre|post]-[user]. The option will allow you to run a specific step command by specified user. Make sure the user exists and present in passwd inside the target container.

Am I doing it wrong?

**Comment by m90** [comment]
User and command are passed as different labels. The command is passed like this:

```yml
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'something -arg 1'
```

If you additionally want to run the command as a non-root user, its name is passed in its own label:

```yml
    labels:
      - docker-volume-backup.archive-pre.user=www-data
      - docker-volume-backup.archive-pre=/bin/sh -c 'something -arg 1'
```

**Comment by erwanlpfr** [comment]
You rock ! Thank you !
