### ISSUE TITLE
Is it possible to update shoutrrr version?

### ISSUE THREAD

**Issue by ba-tno** [offen/docker-volume-backup#212]
**Is your feature request related to a problem? Please describe.**

I would like to use [ntfy.sh](https://ntfy.sh/) to send me notifications when a backup fails. This is a [supported service on shoutrrr](https://containrrr.dev/shoutrrr/0.7/services/overview/), but only since version 0.7.
Currently docker-volume-backup seems to be using version 0.5 as the config file/docs say:

> Notifications (email, Slack, etc.) can be sent out when a backup run finishes.
> Configuration is provided as a comma-separated list of URLs as consumed
> by `shoutrrr`: https://containrrr.dev/shoutrrr/v0.5/services/overview/

**Describe the solution you'd like**

An update of the shoutrrr dependency to the latest version would resolve this issue.

**Describe alternatives you've considered**

I've tried sending e-mail as that is supported by the current shoutrrr version, but I could not get that to work.

**Additional context**

N/A

**Comment by m90** [comment]
According to the go.mod file, it seems version 0.6 is used, not sure why the docs point towards 0.5. if you or someone else wants to open a PR that updates the library to 0.7 __without breaking changes for current users__ I'd be happy to merge and release it. Else, updating the documentation accordingly would also be appreciated.

**Comment by m90** [comment]
I updated the docs to reference the correct version. If anyone still wants to look into updating the library itself (this is mostly about reading the release notes and double checking for user facing breaking changes), I'd still be in support of doing this.

**Comment by ba-tno** [comment]
> I updated the docs to reference the correct version
Sorry, I missed that while working on the pull request, that's why a conflict is introduced.

**Comment by m90** [comment]
This is now released in [v2.27.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.27.0) - Thanks for your contribution.
