### ISSUE TITLE
SMTP configuration with NOTIFICATION_URLS

### ISSUE THREAD

**Issue by vulporuza** [offen/docker-volume-backup#216]
**What are you trying to do?**
I am trying to setup a notification using the Outlook SMTP server.

**What is your current configuration?**
```
NOTIFICATION_URLS=smtp://myemail@hotmail.fr:mypassword@smtp.office365.com:587/?fromAddress=myemail@hotmail.fr&toAddresses=myemail@hotmail.fr
NOTIFICATION_LEVEL="info"
```

**Log output**
```
backup    | time="2023-05-12T17:35:10Z" level=error msg="Backup procedure ran successfully, but an error ocurred calling the registered hooks: runHooks: error running hook: notify: error notifying: sendNotification: error sending message: failed to send using smtp: timed out"
```

**Additional context**
I think the @ in the username is a problem, I tried to escape it with %40, no success.

**Comment by m90** [comment]
In case your URLs are encoded as described here https://github.com/offen/docker-volume-backup#use-special-characters-in-notification-urls and you are seeing the error above, I assume the error message is stating what's going on: something server side times out. Why that is, is hard for me to tell right now, and probably unrelated to this image.

**Comment by m90** [comment]
Closing this, as there doesn't seem to be anything actionable from my end. If you find out more details about the issue, feel free to reopen.
