### ISSUE TITLE
Q: backup of non-container files

### ISSUE THREAD

**Issue by lonix1** [offen/docker-volume-backup#244]
Hi, new user here! Very excited at how simple/useful this tool is.

My current backup system is a bunch of very complex bash scripts - I'd like to replace them with this tool.

However my current system backs up:
- host
  - app's docker files, e.g. `docker-compose.yml`, `.env`, secrets
  - app's config files
  - app's logs
  - etc.
- container
  - app's volumes

...But this tool seems to handle only the last item.

How do you folks handle the host items, if at all?

**Comment by m90** [comment]
You can back up any file that you can mount onto the running container, not only volumes. It's mostly just about how you lay out the contents of `/backup`.

See this comment in another issue for an example: https://github.com/offen/docker-volume-backup/issues/40#issuecomment-998148602
