### ISSUE TITLE
Copy data folder of postgres docker container

### ISSUE THREAD

**Issue by zN3utr4l** [offen/docker-volume-backup#245]
I want to make a backup, only for development, of a docker container on which postgres runs, as the main service, but I noticed that without stopping the backups (the data folder), when I go to copy it to another container it is corrupted, so need to stop it, but if I stop it the container shuts down when if you shut down the main service on docker the container shuts down too.

I was wondering if you had any alternative methods or any advice on this.

I also opened an issue on pgbackrest, because I wanted to try to use it but even there you need to stop the service (https://github.com/pgbackrest/pgbackrest/issues/2134).

**Comment by m90** [comment]
If you want to backup a Postgres Database while running, you'll probably need to use something like [pg_dump](https://www.postgresql.org/docs/current/app-pgdump.html) which you can run in a `pre` hook. An example of this approach for MySQL is found in the README: https://github.com/offen/docker-volume-backup#using-mysqldump-to-prepare-the-backup

**Comment by zN3utr4l** [comment]
I am using the timescale extension for postgres, with pg_dump the hypertables are not backed up, which must be done by copying the data in csv ([https://www.postgresql.org/message-id/SA0PR15MB3933C769FD7FDA12296EBD4382589%40SA0PR15MB3933.namprd15.prod. outlook.com](https://www.postgresql.org/message-id/YJDEI9ZRQfAfxdyK%40admin.sibptus.ru))

**Comment by m90** [comment]
In this case I'm not sure I can give you further advice that is in the scope of this tool. _If_ you happen to find a tool that allows you to back up a running Timescale database, you can use it in conjunction with the approach described above in any case.
