### ISSUE TITLE
Docs site

### ISSUE THREAD

**Issue by m90** [offen/docker-volume-backup#252]
The README is getting _very_ long. Maybe it's time to think about a simple documentation site to be hosted on GH pages.

If anyone wants to look into this, I would prefer not to introduce too much tooling, especially not anything that requires `npm install` (maybe Hugo is worth looking into as we'd stay in the Go ecosystem). Also, it would be nice if the source for the documentation would still be easily readable in the GitHub UI.

**Comment by MaxJa4** [comment]
When using Hugo, we could just use Markdown ([Docs](https://gohugo.io/content-management/formats/)) to keep it easy to edit and read.

**Comment by m90** [comment]
Another very simple option would be using GitHub Pages' built in Jekyll support using this theme https://github.com/just-the-docs/just-the-docs (which is also what is used for https://docs.offen.dev/)

**Comment by MaxJa4** [comment]
Haven't used Jekyll or GH pages yet. I took a look and I'm not quite sure where to start and set it up.
If you would set up the repo / structure for it to work, I could afterwards help migrating and adjusting the contents for the docs if you like.

**Comment by m90** [comment]
Yeah, I'll see if I can get it set up some time soon. We can migrate the content gradually by duplicating and then wipe the README once ready.

**Comment by m90** [comment]
I started working on this here https://github.com/offen/docker-volume-backup/tree/docs-site - will probably take a while until I figured out everything.
