### ISSUE TITLE
Use more efficient drop-in replacements for compression

### ISSUE THREAD

**Issue by MaxJa4** [offen/docker-volume-backup#265]
## Is your feature request related to a problem?

Currently, `compress/gzip` is the default compression option for compatibility reasons, since the way faster `zstd` is not compatible with that file format.
From the same author from whom we use the `zstd` library (klauspost) exist more compression libraries, which are optimized versions of their standard implementation.

I tested these two drop-in replacements for `compress/gzip`:
- `github.com/klauspost/compress/gzip` -> [optimized gzip](https://pkg.go.dev/github.com/klauspost/compress/gzip) implementation, still as specified in gzip standard [spec](https://www.rfc-editor.org/rfc/rfc1952.html)
- `github.com/klauspost/pgzip` -> [parallelized version](https://github.com/klauspost/pgzip) of the optimized gzip, therefore also compatible

<details><summary>Test setup</summary>
<p>

**HW**: i7 13700KF, 32GB RAM, PCIe 4.0 NVMe SSD with ~7 GB/s read (sequential)
**SW**: Win10, Go v1.21.0, klauspost pkgs v1.16.7
**Parameters**: Compression level = 4 for all (default for zstd)
**Test data used**: Full Silesia Corpus contents ([link](https://sun.aei.polsl.pl/~sdeor/index.php?page=silesia))
**Methodology**: Read file (tar'ed test data), de-/compress in memory (no file writing)

</p>
</details> 

<details><summary>Results</summary>
<p>

| Package        | File size after | Compression | Decompression |
|------------|-----------|-------------|---------------|
| Gzip orignal | 33,54%    | 2152ms      | 863.1ms       |
| Gzip klauspost  | 34.29%    | 1249ms      | 711.4ms       |
| PGzip klauspost | 34.37%    | 246.5ms     | 674.0ms       |
| Zstd for reference | 31.89%    | 672.0ms     | 198.6ms       |

</p>
</details> 

## Describe the solution you'd like

To make existing `.tar.gz` / `gzip` setups benefit from vastly superior compression speeds (~1.7x with Gzip, ~8.7x with PGzip) and slightly improved decompression speeds while preserving compatibility, I'm suggesting using one of the optimized `gzip` implementations as drop-in replacement.
Note, that it might not be desirable in an automated/unsupervised backup scenario to use all available CPU power for compression like with `PGzip`'s parallelism (level can be adjusted though), as live production workloads could be influenced by a backup run. The optimized `Gzip` is still single threaded afaik.
While we're at it, maybe it makes sense to introduce three compression presets: fast, default (level 4 like here and default for all packages afaik), best. The user can then prioritize downtime (fast preset) or storage size/cost (best preset). Not set would be default like now.

If you see the need for more testing, feel free to suggest more.

**Comment by m90** [comment]
Thanks for the research, the numbers look pretty impressive. As this definitely is a bottleneck for users, I think we should definitley leverage one of the options. I am just not sure which one yet.

## Option 1 :Replace stdlib gzip with github.com/klauspost/compress/gzip

This would be pretty straightforward and has zero user facing changes. Downside is: we know it could be even faster.

## Option 2 :Replace stdlib gzip with github.com/klauspost/pgzip

Probably also pretty straightforward, and gives us maximum performance. Users that do not set resource limits on their containers might run into surprises.

## Option 3: Allow the user to choose

Very flexible and allows users to choose their preferred tradeoff. I have trouble coming up with a configuration mechanism that wouldn't confuse users.

----

Right now I'm leaning towards option 1 or 2.

Maybe it's also an to introduce a `GZIP_PARALLELISM` parameter with a default of `1` that then picks one of the libraries. But maybe this is too complicated already.

What do you think?

**Comment by MaxJa4** [comment]
I'd prefer to use `PGzip` with the `GZIP_PARALLELISM` setting, defaulting to `1`. A serious user would have at least a quick look that the env variables and can set this to any number higher than `1`. This would mean no unwanted resource use from setting this to `core-count` (like it is for `PGzip`). So I'd propose to use `PGzip` together with the parallelism option.

This can be set easily, but also requires to set the block size (default is 1MB) for the compression. I'll experiment with this, to know whether our specific use case benefits from changing it to another value by default (wouldn't make it configurable tbh). Also, I'll compare `Gzip` with `PGzip` while the parallelism is set to one (if its the same like I'd expect or better/worse).

**Comment by MaxJa4** [comment]
Updated the benchmark suite to use the proper `go test -bench` and including memory allocations now.
Also removed the file reading from the measurements by doing that beforehand.
Note: Memory allocation is measured in sum per run, not max. allocation peak (at one time).

<details><summary>Result overview</summary>
<p>

| Pkg          | Comp. time | Comp. mem-alloc | Decomp. time | Decomp. mem-alloc |
|--------------|------------|-----------------|--------------|-------------------|
| Gzip orig.   |   1980ms   |      269MB      |     878ms    |       1601MB      |
| Gzip opt.    |   1101ms   |      269MB      |     694ms    |       1596MB      |
| PGzip Full   |    116ms   |      344MB      |     624ms    |       1600MB      |
| PGzip Single |    564ms   |      232MB      |     624ms    |       1600MB      |
| Zstd (ref)   |    655ms   |      257MB      |     350ms    |       1614MB      |

`PGzip Full` = full parallelism (all threads)
`PGzip Single` = just one thread

</p>
</details> 

Blocksize tests for `PGzip` ("Full", all threads):

<details><summary>PGzip results</summary>
<p>

| Blocksize        | Comp. time | Comp. mem-alloc |
|------------------|------------|-----------------|
| 512KB            |    115ms   |      274MB      |
| 1024KB (default) |    107ms   |      346MB      |
| 2048KB           |    105ms   |      408MB      |
| 10240KB          |    156ms   |      807MB      |

--> Would recommend to stick with the default block size and just set the parallelism level to `GZIP_PARALLELISM` with a default of `1` for compatability.

</p>
</details>

**Comment by MaxJa4** [comment]
More `PGzip` tests (the last ones). This time, compression ratio and compression level was compared (because Gzip-Orig level 4 seems to be Gzip-Opt level 5 in terms of file size).
Also, note that PGzip did use 2 threads even though 1 was specified for "Single". Maybe the Windows scheduler does something there, but that's the reason why it's ~2x faster than regular Gzip-Opt.

<details><summary>Comp. Ratio & Comp. Speed</summary>
<p>

| Comp. level -> Pkg | 3           | 4 (default)  | 5            |
|--------------------|-------------|--------------|--------------|
| GZip orig.         |      -      | _2.98x 2207ms_ | -            |
| GZip opt.          | 2.82x 901ms | 2.92x 1107ms | _2.97x 1305ms_ |
| PGZip Single       | 2.81x 474ms |  2.91x 552ms | _2.96x 654ms_  |
| ZStd (ref)         |      -      |  3.14x 794ms | -            |

</p>
</details>

**Comment by m90** [comment]
> Replace `GZip orig` with `PGZip` with a `GZIP_PARALLELISM` env variable which defaults to `1`.
> If someone sets it to `-1`, then all available threads shall be used ("Full" here) which is even faster than `Zstd` (but Zstd is still better at compression ratio).

Sounds good to me :+1:

**Comment by m90** [comment]
This is released in [v2.33.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.33.0)

**Comment by m90** [comment]
Some observations from my end after deploying this feature:

- smallish archives (< 100MB) seem to have gotten slightly bigger
- big archives (> 1GB) seem to have gotten slightly smaller
- when using the defaults, speed was pretty much like before, maybe a tad slower (~10%)
- when setting `GZIP_PARALLELISM` to `2`, backup times got considerably faster (~60%)

**Comment by MaxJa4** [comment]
Interesting... how compressible are the small and big archives?
