### ISSUE TITLE
FR: Add seperate success/fail notification URLs

### ISSUE THREAD

**Issue by SolomonHD** [offen/docker-volume-backup#277]
**Is your feature request related to a problem? Please describe.**

I am using Discord and I want the success and fail notifications. I would like a channel alert during the fail messages. I approached [shoutrrr](https://github.com/containrrr/shoutrrr/discussions/379) about this and it's on their radar but no timetable. 

**Describe the solution you'd like**

Another approach would be on the offen side, you could have separate success/fail variables for the notifications, only overriding NOTIFICATION_URLS if they're set, thus not changing current behavior. Then I could set the failure channel to alert me on message received.

**Comment by m90** [comment]
While it's not really hard to implement, I'm not sure if this tool should be concerned with message routing, "Why do my notifications not arrive" is a common support request and having even more configuration options will make this even harder to debug.

**Comment by m90** [comment]
Closing this as it's probably not going to happen soon.
