### ISSUE TITLE
Documentation issues with custom commands

### ISSUE THREAD

**Issue by nigelm** [offen/docker-volume-backup#287]
**Describe the bug**

Documentation issues with custom commands:-

1. The docker socket must be mounted for custom commands to work (needs to see labels) - the socket is not just for stopping containers.
2. The docker-compose labels are seen across the whole docker estate, so unless you use unique `EXEC_LABEL`s, should you have multiple `docker-volume-backup` sets, you will end up running *all* the custom commands across the estate even those within entirely different docker-compose configurations

**Comment by m90** [comment]
Thanks for raising these points. Would you mind opening a PR that rectifies these things in places where you found them to be misleading?
