### ISSUE TITLE
misleading error message

### ISSUE THREAD

**Issue by pixxon** [offen/docker-volume-backup#291]
**Describe the bug**
Wrong secret key provides misleading error message. Not sure if it can be handled, but I ran into this and couldn't find a matching issue with some guidance. While doing a manual backup, I got the following error:
```
➜  pixxon@pixxon-pc backups docker exec -it 5497617d3cf5 backup
time=2023-10-27T23:07:44.137Z level=INFO msg="Created backup of `/backup` at `/tmp/backup-2023-10-27T23-07-43.tar.gz`."
time=2023-10-27T23:07:44.160Z level=ERROR msg="Fatal error running backup: copyArchive: error copying archive: (*s3Storage).Copy: error uploading backup to remote storage: [Message]: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.', [Code]: SignatureDoesNotMatch, [StatusCode]: 403"
time=2023-10-27T23:07:44.164Z level=INFO msg="Removed tar file `/tmp/backup-2023-10-27T23-07-43.tar.gz`."
```

**To Reproduce**
1. have stack using secrets ready ( `AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/minio_secret_key` is the only important part )
2. `echo "ObviouslyNotASecretKey" | docker secret create minio_secret_key -`
3. `docker stack deploy -c mystack.yaml mystack`
4. `docker ps` ( find backup container id )
5. `docker exec -it <container_id> backup`

**Expected behavior**
Some error message that indicates the newline at the end of the secret or just a general secret key is invalid message.

**Version (please complete the following information):**
 - Image Version: v2.33.0
 - Docker Client Version: 23.0.3
 - Docker Engine Version: 20.10.14

**Additional context**
The obvious solution is to use `printf` instead of `echo`, but my 1am brain was able to walk into this problem and was kinda hard to diagnose the trailing new line.

**Comment by m90** [comment]
I doubt there is any client side validation we can do here as generic S3 backends could allow any pattern to be used as the secret key. When using MinIO, `ObviouslyNotASecretKey`, would be a perfectly valid secret key. It's unfortunate the error message returned by the server is a bit misleading in your case, but this cannot be solved by this tool.

That being said, I wonder if this tool.should trim trailing and leading whitespace from secrets that are read from files. I will need to check if this is common behavior in other software.

**Comment by pixxon** [comment]
I was hoping there is a server side validation for the secret key, but from what I have seen, these messages are specified in AWS S3 and there is only reponse for invalid access key, not secret key.

Trimming is sort of weird, Authentik trims the newlines, but Postgres doesn't. In my experience they are very inconsistent with this behaviour in general. Maybe just some note about it in the `_FILE` note could be helpful. ( Or honestly just this ticket showing up can already save some time for users. )

**Comment by m90** [comment]
I added a note about potential traling and leading whitespace to the docs. Thanks for raising this issue.
