### ISSUE TITLE
Notify Uptime-Kuma

### ISSUE THREAD

**Issue by mcfrojd** [offen/docker-volume-backup#297]
**What are you trying to do?**

I would like to send a push to my uptime-kuma instance to let it know that the daily backup was executed.

**What is your current configuration?**

I tried shouterrr's "generic webhook url" with uptime-kumas push url but that did not work.
`generic+https://uptime.myserver.com/api/push/HhdRbdYzZD?status=up&msg=OK&ping=`

**Log output**

```
time=2023-11-01T12:02:12.470Z level=INFO msg="Stopping 2 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 7 running container(s)."
time=2023-11-01T12:02:13.539Z level=INFO msg="Created backup of `/backup` at `/tmp/daily-backup-2023-11-01T12-02-12.tar.gz`."
time=2023-11-01T12:02:14.038Z level=INFO msg="Restarted 2 container(s) and the matching service(s)."
time=2023-11-01T12:02:14.066Z level=INFO msg="Stored copy of backup `/tmp/daily-backup-2023-11-01T12-02-12.tar.gz` in `/archive`." storage=Local
time=2023-11-01T12:02:14.068Z level=INFO msg="None of 3 existing backups were pruned." storage=Local
time=2023-11-01T12:02:14.069Z level=INFO msg="Removed tar file `/tmp/daily-backup-2023-11-01T12-02-12.tar.gz`."
time=2023-11-01T12:02:14.361Z level=ERROR msg="Backup procedure ran successfully, but an error ocurred calling the registered hooks: runHooks: error running hook: notify: error notifying: sendNotification: error sending message: an error occurred while sending notification to generic webhook: server returned response status code 400 Bad Request"
```

**Additional context**

Maybe someone know of another method to let uptime-kuma know that the daily backup was run?

**Comment by m90** [comment]
I guess you could use an approach as described here https://github.com/offen/docker-volume-backup/issues/159 where you use a [custom command](https://offen.github.io/docker-volume-backup/how-tos/run-custom-commands.html) to ping your endpoint using `wget`?

**Comment by mcfrojd** [comment]
Thanx for your answer, it seems to work even if i get a error message in the output.

I added this label to one of my dockers
```
labels:
  - docker-volume-backup.copy-post=/bin/sh -c 'wget https://uptime.myserver.com/api/push/HhdRbdYzZD?status=up&msg=OK&ping='
```
And uptime-kuma gets the push as wanted.

I do get a error message in the output, but maybe i can just ignore that?
```
time=2023-11-01T12:35:35.030Z level=INFO msg="Running docker-volume-backup.copy-post command /bin/sh -c 'wget https://uptime.myserver.com/api/push/HhdRbdYzZD?status=up&msg=OK&ping=' for container xxxxxx"
time=2023-11-01T12:35:35.521Z level=ERROR msg="Fatal error running backup: runLabeledCommands: error from errgroup: runLabeledCommands: error executing command: exec: running command exited 126"

```

**Comment by mcfrojd** [comment]
> `wget` by default saves the output to a file, and I would assume this doesn't work for whatever reasons (likely permissions) in your setup. Could you try piping the output to /dev/null or just printing it to stdout instead?

Im afraid im not that linux savvy so im not sure what to do to to pipe the output or print to stdout.
Maybe you can direct me or show an example what to add and where?

**Comment by m90** [comment]
https://stackoverflow.com/a/9691442/797194

**Comment by mcfrojd** [comment]
I tried most variants from the examples that you provided and then some.
And now i notised that uptime-kuma only registers the first wget from the docker.
When i go back to the wget variant that worked the first time (but gave the error message) it wouldent work the second time.
I can use the push url in a browser and that gets triggered, but not with the wget from the docker..
I might look into trying to add a script that makes the push call and then call that script as a copy-post command.

**Comment by mcfrojd** [comment]
I seem to got it to work so that uptime-kuma registers more than the first push.
When i use this copy-post command uptime-kuma gets the pushes, and there is no more error messages

`- docker-volume-backup.copy-post=/bin/sh -c 'wget -qO- https://uptime.myserver.com/api/push/JHfghF2DzTR?status=up&msg=OK&ping= &> /dev/null'`
