### ISSUE TITLE
Send email notification with O365 SMTP

### ISSUE THREAD

**Issue by ZoR3oL** [offen/docker-volume-backup#298]
**What are you trying to do?**

Send notification of backup job with O365 SMTP. Backup worked as expected, but we haven't any email received.

**What is your current configuration?**
NOTIFICATION_URLS=smtp://email@domain.com:PASSWORD@smtp.office365.com:25/?fromAddress=email@domain.com&toAddresses=email2@domain.com

**Log output**
No log output

**Additional context**
No Additional context

**Comment by m90** [comment]
It's impossible for me to give any support with that little information. Maybe this is similar to https://github.com/offen/docker-volume-backup/issues/216
