### ISSUE TITLE
S3 API with Backblaze B2: The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by cbenard** [offen/docker-volume-backup#322]
On January 5, 2024, after running successfully, nightly for over a year, I started getting a daily failure with the following message and log:

```
Running docker-volume-backup failed with error: pruneBackups: error pruning backups: The XML you provided was not well-formed or did not validate against our published schema

Log output of the failed run was:

time=2024-01-07T09:00:10.996Z level=INFO msg="Stopping 1 container(s) labeled `docker-volume-backup.stop-during-backup=true` out of 5 running container(s)."
time=2024-01-07T09:01:01.876Z level=INFO msg="Created backup of `/backup` at `/tmp/backup-2024-01-07T09-00-08.tar.gz`."
time=2024-01-07T09:01:16.346Z level=INFO msg="Restarted 1 container(s) and the matching service(s)."
time=2024-01-07T09:01:20.113Z level=INFO msg="Encrypted backup using given passphrase, saving as `/tmp/backup-2024-01-07T09-00-08.tar.gz.gpg`."
time=2024-01-07T09:01:27.181Z level=INFO msg="Uploaded a copy of backup `/tmp/backup-2024-01-07T09-00-08.tar.gz.gpg` to bucket `backup-cbenard`." storage=S3
time=2024-01-07T09:01:27.365Z level=ERROR msg="Fatal error running backup: pruneBackups: error pruning backups: The XML you provided was not well-formed or did not validate against our published schema"
time=2024-01-07T09:01:27.368Z level=INFO msg="Removed tar file `/tmp/backup-2024-01-07T09-00-08.tar.gz`."
time=2024-01-07T09:01:27.376Z level=INFO msg="Removed GPG file `/tmp/backup-2024-01-07T09-00-08.tar.gz.gpg`."
```

**To Reproduce**
1. Use S3 API against Backblaze B2 with prune enabled

I don't know the XML being sent, so I cannot debug.

**Expected behavior** : Prune would continue working as usual.

**Version (please complete the following information):**
 - Image Version: Tag: v2, Image ID: ba0854c8b9da
 - Docker Version: Docker version 20.10.20, build 9fdeb9c3de2f2d9f5799be373f27b2f9df44609d
 - Docker Compose Version (if applicable): docker-compose version 1.29.2, build unknown

**Additional context**

Environment:

```
   environment:
      - "BACKUP_CRON_EXPRESSION=0 9 * * *" # This will be in UTC
      - BACKUP_RETENTION_DAYS=60
      - AWS_ENDPOINT=${BACKUP_AWS_ENDPOINT}
      - AWS_S3_BUCKET_NAME=${BACKUP_AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${BACKUP_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BACKUP_AWS_SECRET_ACCESS_KEY}
      - AWS_S3_PATH=${BACKUP_AWS_S3_PATH}
      - GPG_PASSPHRASE=${BACKUP_GPG_PASSPHRASE}
      - NOTIFICATION_URLS=smtp://${SMTP_USERNAME}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT}/?fromAddress=${BACKUP_SMTP_FROM}&toAddresses=${>
```

**Comment by m90** [comment]
Did you update your image version in use before this happened?

I have to admit this sounds a bit like an issue with B2, maybe sth intermittent, at least the [library used for interacting with the S3 backends](https://github.com/minio/minio-go) should be stable enough not to surface such basic errors out of the blue.

I also cannot find anything about similar errors in minio's issues https://github.com/minio/minio-go/issues or https://github.com/minio/mc/issues

Do you know if it's possible for you to delete files from B2 (it seems this is what it's failing at) using a different client, e.g. the AWS CLI or similar?

**Comment by m90** [comment]
I've never used R2 myself, but it would probably also be worth it to check their changelogs or similar for anything that happened recently.

There is no built in way to dump the XML that is being sent, no. In case you are fine with building a custom image and using it, you could enable HTTP tracing on the client though https://min.io/docs/minio/linux/developers/go/API.html#TraceOn

**Comment by cbenard** [comment]
`s3cmd ls` and `s3cmd rm` worked fine once configured with the same env values, so the problem doesn't appear to be with B2.

**Comment by cbenard** [comment]
> There is no built in way to dump the XML that is being sent, no. In case you are fine with building a custom image and using it, you could enable HTTP tracing on the client though https://min.io/docs/minio/linux/developers/go/API.html#traceon-outputstream-io-writer

I'm not familiar enough with Go to do that. I know some other languages. If you provide a test image label (even if in another public registry), I could try that and provide output.

Could you tell me what operation it is trying to do other than the equivalent of a `s3cmd ls` and repeated `s3cmd rm`? Maybe I could try to repro there?

**Comment by cbenard** [comment]
Also, B2 is totally free under 10GB and some amount of egress. No credit card is even needed. Is there a way you could try to locally repro?

**Comment by m90** [comment]
Since this tool is just consuming an upstream library, maybe it'd be a good idea to open an issue there: https://github.com/minio/minio-go referencing this issue. Even if we'd find out what exactly goes wrong, I wouldn't even be able to fix it here.

The `prune` method for the S3 storage calls `ListObjects` and `RemoveObjects` APIs: https://github.com/offen/docker-volume-backup/blob/64daf7b1324d36bd1603095f4ff07cff6971b7e9/internal/storage/s3/s3.go#L143-L192

**Comment by cbenard** [comment]
It looks like it is doing the equivalent of this, which works fine:

```sh
# s3cmd ls --recursive "s3://my-bucket-name/sub/path/backup-*"`
2023-11-07 09:01     36380038  s3://my-bucket-name/sub/path/backup-2023-11-07T09-00-05.tar.gz.gpg
2023-11-08 09:00     36385764  s3://my-bucket-name/sub/path/backup-2023-11-08T09-00-05.tar.gz.gpg
... and so on
```

I'm not totally familiar with Go's "channel" mechanism for concurrency or how it's interacting with the matches, so I don't know 100% how to translate the next part, but it looks like removing multiple objects at once, so I tried this:

```sh
# s3cmd rm s3://my-bucket-name/sub/path/backup-2023-11-07T09-00-05.tar.gz.gpg s3://my-bucket-name/sub/path/backup-2023-11-08T09-00-05.tar.gz.gpg
delete: 's3://my-bucket-name/sub/path/backup-2023-11-07T09-00-05.tar.gz.gpg'
delete: 's3://my-bucket-name/sub/path/backup-2023-11-08T09-00-05.tar.gz.gpg'
```

I'm not sure if that's using a plural "RemoveObjects" or simply iterating through the list with single deletes.

Is there a way you can provide a custom image to debug the XML? Apologies for the request, but I can't repro with a cmdline tool.

**Comment by m90** [comment]
If B2 complains about XML not matching their schema, concurrency should not be the issue. I.e. what you are doing maps pretty closely to what is happening with this tool. If I were you, I'd open an issue with the MinIO client https://github.com/minio/minio-go and/or contact Backblaze support. The amount of actionable things to do in this repo unfortunately is very limited regarding this issue.

One thing before doing that, which is probably helpful is to update your version of `docker-volume-backup` to `v2.35.0` so we can be sure you are also using the latest version of the MinIO client.

**Comment by cbenard** [comment]
I ran a watchtower update. It didn't see any updates for this container. Is the `v2` tag not pointed at `v2.35.0`? Can you, if not? I'm using the Docker Hub repo.

I'm not able to open an issue with minio-go, because what could I tell them for steps to reproduce? I don't have the ability to set up a Go repro. They'd also probably request I turn on that XML debug logging to see what XML is being produced.

If I contact Backblaze support, they also will want to know what I'm sending (the XML).

Without the debug output from the tool, I can't really see what's wrong or attempt to open a case with either entity?

Could you let me know about the volume tag? I'd prefer not to change the compose to use that specific tag, since it won't get upgraded then by watchtower in the future, but I will, if necessary.

Also, is there a way you could:
1) Add a ENV flag to turn on the debug logging for the S3 XML writer?
or
2) Create a custom image tag for this issue that I could use temporarily to do the same thing?

**Comment by cbenard** [comment]
Please ignore the image tag questions about v2 in the response above. I don't know what's up with watchtower. I can see on Docker Hub that the images are the same.

**Comment by m90** [comment]
If you pull on a clean system, `v2` and `v2.35.0` should be synoym as of now, yes. I just couldn't find the `ba0854c8b9da` you are referencing on your original issue.

**Comment by m90** [comment]
If you're looking to get the XML sent, you could also run the tool locally and use Wireshark or similar to tap on the outgoing request. In the end, it's just HTTP.

**Comment by cbenard** [comment]
```sh
# docker pull offen/docker-volume-backup:v2
v2: Pulling from offen/docker-volume-backup
Digest: sha256:d0c78fa9558ecf538d9da08e5dee980ce96d7c2e4ff62f8af35ab2a21d102102
Status: Image is up to date for offen/docker-volume-backup:v2
docker.io/offen/docker-volume-backup:v2

# docker image ls --digests | grep offen
offen/docker-volume-backup   v2        sha256:d0c78fa9558ecf538d9da08e5dee980ce96d7c2e4ff62f8af35ab2a21d102102   ba0854c8b9da   2 weeks ago     31.3MB
```

The `ba0854c8b9da` I provided was an image ID, not the digest hash. Sorry.

However, doing a pull isn't showing anything to update. It shows 2 weeks old, and I can't find that digest ID on Docker Hub. Am I doing something wrong here? It seems odd that watchtower doesn't see anything to update and neither does my `docker pull`.

**Comment by cbenard** [comment]
> If you're looking to get the XML sent, you could also run the tool locally and use Wireshark or similar to tap on the outgoing request. In the end, it's just HTTP.

I can't do this, because everything is containerized and it's HTTPS, not HTTP. If you're not able to assist with getting the debug output, I guess I'm just totally screwed, unfortunately.

**Comment by cbenard** [comment]
Even manually pulling `v2.35.0` shows the same hash:

```sh
# docker image ls --digests | grep offen
offen/docker-volume-backup   v2        sha256:d0c78fa9558ecf538d9da08e5dee980ce96d7c2e4ff62f8af35ab2a21d102102   ba0854c8b9da   2 weeks ago     31.3MB
offen/docker-volume-backup   v2.35.0   sha256:d0c78fa9558ecf538d9da08e5dee980ce96d7c2e4ff62f8af35ab2a21d102102   ba0854c8b9da   2 weeks ago     31.3MB
```

From [Docker Hub](https://hub.docker.com/layers/offen/docker-volume-backup/v2/images/sha256-b745d1beacda36b74e11d8b3084eac406dab20ac8e8d3a7e9bffa97aad1823ee?context=explore&tab=vulnerabilities):

```
offen/docker-volume-backup:v2
DIGEST:sha256:b745d1beacda36b74e11d8b3084eac406dab20ac8e8d3a7e9bffa97aad1823ee
```

I don't get it.

**Comment by m90** [comment]
> I'm not able to open an issue with minio-go, because what could I tell them for steps to reproduce? I don't have the ability to set up a Go repro. They'd also probably request I turn on that XML debug logging to see what XML is being produced.

I wouldn't be too scared about this. The worst thing that could happen is that they don't have any feedback.

I personally don't have the time to debug this right now, and I'm also still skeptical it's something that can even be solved in here. It still sounds like either a schema change in B2 (my guess) or a bug in the Minio client (unlikely).

I'll see the same digest that you see

```
➜  ~ docker pull offen/docker-volume-backup:v2
v2: Pulling from offen/docker-volume-backup
661ff4d9561e: Pull complete 
4f4fb700ef54: Pull complete 
5e6cccf1f5aa: Pull complete 
0b84ebb6ea5c: Pull complete 
0b3f91fe90c6: Pull complete 
Digest: sha256:d0c78fa9558ecf538d9da08e5dee980ce96d7c2e4ff62f8af35ab2a21d102102
Status: Downloaded newer image for offen/docker-volume-backup:v2
docker.io/offen/docker-volume-backup:v2
```

Not sure why Docker hub shows sth different tbh.

**Comment by cbenard** [comment]
Apparently [this is a known problem](https://github.com/docker/hub-feedback/issues/1925). You can't just compare the hashes for some reason.

So I'd say I'm using `v2.35.0` since the hashes match locally when I do a `pull` for `v2.35.0`.

**Comment by cbenard** [comment]
minio-go closed the issue, as expected. If you get time at some point to enable (via a switch or a custom image) the XML trace output, I would sincerely appreciate it.

Without it, there's nothing for me to tell Backblaze. I can't open a case with them and say "DeleteObjects fails, but I can't tell you what I'm sending".

**Comment by m90** [comment]
I can't add more than what's said in the other issue. It works with S3 and MinIO, and if the change appeared out of the blue, it's likely an issue with Backblaze. I cannot spend time on debugging their issues, I am sorry.

**Comment by cbenard** [comment]
I understand, and apologies if you already understood what I'm asking, but I wanted to rephrase one more time to clarify, just in case.

I'm not asking you to troubleshoot anything with Backblaze B2. I would simply like debug output, like a `-v` on many apps, that could be turned on with an ENV var like your many other vars. That would output the XML being sent.

I would then use that XML myself to work with Backblaze, without involving you. The XML debug output would allow anyone to troubleshoot issues with any S3 API provider, not just Backblaze, and not just me.

I just wanted to clarify, in case it sounded like I was trying to get you to do something with Backblaze directly or specifically for them.

Apologies if you already understood that and your response still applies. I'm just a bit helpless without the output to go to Backblaze myself.

Thank you.
