### ISSUE TITLE
panic: unable to acquire file lock

### ISSUE THREAD

**Issue by zN3utr4l** [offen/docker-volume-backup#34]
**Docker compose v 3.9**

    backup:
        image: offen/docker-volume-backup:v2.5.0
        logging:
          driver: "json-file"
          options:
            max-file: 6
            max-size: 1024m
        user: root
        restart: always
        mem_limit: 512m
        mem_reservation: 100m
        container_name: backup_new
        environment:         
            - BACKUP_CRON_EXPRESSION=$BACKUP_CRON_EXPRESSION
            - BACKUP_FILENAME=$BACKUP_FILENAME
            - BACKUP_PRUNING_PREFIX=$BACKUP_PRUNING_PREFIX
            - BACKUP_RETENTION_DAYS=$BACKUP_RETENTION_DAYS
            - BACKUP_FROM_SNAPSHOT=$BACKUP_FROM_SNAPSHOT
        volumes:
            - mongo_archive:/backup/mongo-archive:ro
            - timescale_data:/backup/timescale-data:ro         
            - ${HOME}:/archive 

BACKUP_CRON_EXPRESSION='00 */12 * * *'
BACKUP_FILENAME='backup-%Y-%m-%dT%H-%M-%S.tar.gz'
BACKUP_PRUNING_PREFIX='backup-'
BACKUP_RETENTION_DAYS=7
BACKUP_FROM_SNAPSHOT='true'

HOME='C:\BackupVolume'

```
time="2021-12-02T15:34:09Z" level=info msg="Created snapshot of `/backup` at `/tmp/backup`."

**panic: unable to acquire file lock

goroutine 1 [running]:
main.lock({0xa1950b, 0x21})
/app/cmd/backup/main.go:677 +0xce
main.main()
/app/cmd/backup/main.go:35 +0x45**

time="2021-12-02T15:38:29Z" level=info msg="Created backup of `/tmp/backup` at `/tmp/backup-2021-12-02T15-34-00.tar.gz`."
time="2021-12-02T15:38:56Z" level=info msg="Stored copy of backup `/tmp/backup-2021-12-02T15-34-00.tar.gz` in local archive `/archive`."
time="2021-12-02T15:38:56Z" level=info msg="Sleeping for 1m0s before pruning backups."
time="2021-12-02T15:39:56Z" level=info msg="None of 6 local backup(s) were pruned."
time="2021-12-02T15:39:56Z" level=info msg="Removed snapshot `/tmp/backup`."
time="2021-12-02T15:39:56Z" level=info msg="Removed tar file `/tmp/backup-2021-12-02T15-34-00.tar.gz`."
time="2021-12-02T15:39:56Z" level=info msg="Finished running backup tasks."
```

**Comment by m90** [comment]
This looks as if your setup somehow triggers two concurrent invocations of the backup procedure and the second invocation fails because it cannot acquire the exclusive lock that guarantees no concurrent invocations are happening.

My initial suspicion would be that Busybox's `cron` does not like your cron expression, but then again, I'm not sure why, docs themselves are rather stiff lipped:

```
crontab
crontab [-c DIR] [-u USER] [-ler]|[FILE]

        -c      Crontab directory
        -u      User
        -l      List crontab
        -e      Edit crontab
        -r      Delete crontab
        FILE    Replace crontab by FILE ('-': stdin)
```

Could you try using a super simple cron expression like `0 12 * * *` and check whether the issue persists?

**Comment by m90** [comment]
An alternative syntax for your use case would be something like `0 0,12 * * *`

**Comment by zN3utr4l** [comment]
Thanks, I'll try to use the latter `(0 0,12 * * *) `and I'll let you know in a couple of days

**Comment by zN3utr4l** [comment]
I confirm, It's working : (0 0,12 * * *)

**Comment by m90** [comment]
Good to know and thanks for the feedback. I'll add a note to the README about the cron syntax being limited in strange ways.

**Comment by m90** [comment]
So it seems busybox should support the syntax you have been using:

```
/ # crontab -l
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
```

which makes me wonder if someone expands that `*` in the expression when creating the crontab entry. I'll need to do some further investigation on this.

**Comment by m90** [comment]
It seems this is caused by the `00` in your example. Not sure why, but I cannot repro the issue when using single `0`s in any way.
