### ISSUE TITLE
archive-pre is triggered on each container backup instead of just container with exec-label

### ISSUE THREAD

**Issue by claytonjs** [offen/docker-volume-backup#380]
Looking for help as  I can't seem to figure out what I'm doing wrong.

I'm backing up 14 different containers. Each has its own .env file and one of the containers is postgresql. For that container I have the following labels in the docker-compose so that before the backup is taken it exports the database dump and after cleans up:

    labels:
      - docker-volume-backup.exec-label=postgresql
      - docker-volume-backup.archive-pre=/bin/sh -c 'pg_dumpall -c -U authentik > /var/lib/postgresql/data/backups/dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql'
      - docker-volume-backup.archive-post=/bin/sh -c 'find /var/lib/postgresql/data/backups/*.sql -mtime +14 -exec rm {} \;'

And in the .env I have:

BACKUP_CRON_EXPRESSION="14 2 * * 0"
BACKUP_SOURCES="/backup/postgresql/backups"
BACKUP_RETENTION_DAYS="65"
BACKUP_PRUNING_PREFIX="postgresql-"
EXEC_LABEL=postgresql

Which does work. However for each container that is getting backed up it's also triggering the docker-volume-backup.archive-pre and docker-volume-backup.archive-post for the postgresql container. I would of though that it should just do it for the container that I have a label for EXEC_LABEL set.

Any help would be appreciated. I'm sure I'm just missing something, just not sure what.

**Comment by m90** [comment]
This is a bit confusing and has come up multiple times already, but it's already too late to change the current behavior:

when you set an `EXEC_LABEL` for a single configuration, you will need to set a (different) value for all other configurations as well in order for commands being skipped in these cases. Right now what happens is:
- the configuration that has `EXEC_LABEL` filters containers based on the value and pick your database container
- the configurations that do not have an `EXEC_LABEL` set assume commands should be run on _all_ containers, thus executing these on the database container as well

I.e. the proper workaround for you would be to set `EXEC_LABEL=none` on your backup container's environment (or in all of the other env files) and then have the env file for your database backup specify the desired value that targets the database container.

**Comment by claytonjs** [comment]
Got it, makes sense now. Thanks for the help.

**Comment by m90** [comment]
Added a note about this in the documentation in 440bcf7
