### ISSUE TITLE
Notifications Delay

### ISSUE THREAD

**Issue by marvintnk** [offen/docker-volume-backup#387]
Is your feature request related to a problem? Please describe.

I use notifications via shoutrrr and gotify. My problem is, that I also backup the gotify container and have it stopped fot the backup. But becaus of that the gotify service is still unavailiable when docker-volume-backups wants to send the notification for the sucessfull backup. Is there any way to implement a delay fot the notification to go out?

Describe the solution you'd like
Any way to set a Delay period until the notifications goes out. I know Watchtower also uses Shoutrr and there is something like this implemented.

**Comment by m90** [comment]
This has already been discussed here: https://github.com/offen/docker-volume-backup/discussions/292
