### ISSUE TITLE
Replace Log line feeds with HTML <br> tag

### ISSUE THREAD

**Issue by vbaidak** [offen/docker-volume-backup#388]
**What are you trying to do?**
I'm trying to generate an HTML email notification. 
Everything works fine, but I need a function, which will replace line feeds (`\n`) in `.Stats.LogOutput` with HTML's `<br>` tags

**Why?**
I want a multiline log, but HTML renders it as a single line. There is a CSS `white-space: pre-line;` setting that renders line feeds correctly, but this setting doesn't work in Outlook, a target platform for notifications.

Maybe I can somehow call `Go`'s replace function inside the template file? (I'm just not very aware of Go)

**Comment by m90** [comment]
The functions available in the templates is documented here: https://pkg.go.dev/text/template#hdr-Functions

It would be possible to add more functions by including them in this tool, but I'd like to prevent sprawl, so I'm a bit hesitant, but open for very generic suggestions.

**Comment by m90** [comment]
Could you just wrap the log output in a `<pre>` element? Or will Outlook also render this incorrectly?

**Comment by vbaidak** [comment]
Yes, `<pre>` works. Just checked it. Thanks for your help
