### ISSUE TITLE
Backup the entire content without directory

### ISSUE THREAD

**Issue by vbaidak** [offen/docker-volume-backup#394]
**What are you trying to do?**
Currently, I have 2 folders and several files inside the `/backup` directory. How can I archive them, so that we don't have `/backup` directory inside the archive, but only it's content?

**Comment by m90** [comment]
That's currently not supported (not sure if a "rootless" tar archive is even expected), but you can definitely strip the `/backup` directory at untar time by using `--strip-components`: https://superuser.com/a/899688

**Comment by vbaidak** [comment]
Yeah, I know about `--strip-components`, just don't wanna keep the root folder in the backups. `tar` supports having multiple directories in root, you may specify them when you do create archive: `tar -zcvf a.tgz a b c`

**Comment by m90** [comment]
Is there anything you cannot do because of the root folder? Or is this merely an "aesthetic" preference?

**Comment by vbaidak** [comment]
Well, it just adds extra work for backup users, who want to unpack. It means they will be required to update their scripts since previously we did not have an extra root folder in backups.
