### ISSUE TITLE
Backup to subfolders

### ISSUE THREAD

**Issue by justinbyoung** [offen/docker-volume-backup#396]
**Is your feature request related to a problem? Please describe.**

I am backing up a number of volumes for a number of docker services using env files in a conf.d config folder and backing up to a local folder. Currently they all just end up in a single folder. I would like to add some organisation to this by dumping the backups into subfolders for each service. I thought that by prefixing a folder name to the start of BACKUP_FILENAME variable that might do what I want. 
e.g. BACKUP_FILENAME="foldername\/backup-%Y-%m-%dT%H-%M-%S.tar.gz"
I can see in the logs this is working when creating the archive in tmp but then just the backup file is copied over to /archive.

**Describe the solution you'd like**

Either to be able to prefix a folder path as in my example
BACKUP_FILENAME="foldername\/backup-%Y-%m-%dT%H-%M-%S.tar.gz"
or have an additional variable to specify a subfolder/s.
e.g.
BACKUP_FOLDER="foldername"

**Describe alternatives you've considered**

Open to any other methods of organising the backup archives.

**Additional context**

**Comment by m90** [comment]
You can already do this by setting [`BACKUP_ARCHIVE`](https://offen.github.io/docker-volume-backup/reference/) to a non-default location (e.g. `/archive/app-1`) in each of your configuration files:

```
# In addition to storing backups remotely, you can also keep local copies.
# Pass a container-local path to store your backups if needed. You also need to
# mount a local folder or Docker volume into that location (`/archive`
# by default) when running the container. In case the specified directory does
# not exist (nothing is mounted) in the container when the backup is running,
# local backups will be skipped. Local paths are also be subject to pruning of
# old backups as defined below.

# BACKUP_ARCHIVE="/archive"
```

Note that in case the directory does not exist backup will be skipped, so you will need to ensure these are created beforehand.

**Comment by justinbyoung** [comment]
Brilliant thanks. I totally missed that option. Works perfectly.
