### ISSUE TITLE
Using labels and yaml file

### ISSUE THREAD

**Issue by danielmbrown603** [offen/docker-volume-backup#40]
Two questions

First question; is there a way to use labels to determine which container to backup? Right now, all my of my container data is in /home/username/docker/AppName. Rather than defining /home/username/docker:ro in my backup app, to narrow down to which apps I want to backup, I am only defining volumes of apps I want to backup. E.g.
-  /home/username/docker/App1
-  /home/username/docker/App2
-  /home/username/docker/App3
Rather, is it possible to define the root docker folder "/home/username/docker:ro" but then use a label to tell the backup tool which apps to backup or not to backup? 

Second question; Is there a way to include the (docker compose) yaml and env files in the same tar.gz?

Thank you

**Comment by m90** [comment]
> Rather, is it possible to define the root docker folder "/home/username/docker:ro" but then use a label to tell the backup tool which apps to backup or not to backup?

Not really, no. I also have to admit that I'm not sure where the benefit of that approach would be as you would still have the same amount of configuration, just elsewhere. Mounting the volume that you want to use as the source also feels quite natural as an interface I feel. In case I am missing something feel free to provide a configuration example before/after?

>  Is there a way to include the (docker compose) yaml and env files in the same tar.gz

There is no built in way, but you could of course just mount any file (including the compose file and others) into `/backup`, something like:

```yml
volumes:
  - app_data:/backup/app_data:ro
  - ./docker-compose.yml:/backup/config/docker-compose.yml
```

**Comment by danielmbrown603** [comment]
Deploying a new container, I try to minimize changes to existing apps deployed. Rely on labels over hardcoding but I hear your point too.

Good point, the composer yaml file is easy to mount. Although I can't get a .env file to mount. My main env file has not filename to it and this isn't working. Any thoughts?

  - ./.env:/backup/config/.env

Thanks again

**Comment by m90** [comment]
Are you sure the file isn't mounted (as opposed to a simple `ls` not showing it)?

```
➜  ~ echo "ok" > .env                                    
➜  ~ docker run --rm -it -v $(pwd)/.env:/root/.env alpine
/ # cat /root/.env 
ok
```

**Comment by danielmbrown603** [comment]
fatfinger on my side. All good now. Thanks!

**Comment by m90** [comment]
No worries.
