### ISSUE TITLE
Remove local backup after upload to S3

### ISSUE THREAD

**Issue by Kavan72** [offen/docker-volume-backup#400]
I've configured the backup of my PostgreSQL Docker instance, where I've set it to take a backup from the last month and upload it to S3. Now, all these backups are also present in the local file system. Is there any way to remove them after uploading to S3?

**Comment by m90** [comment]
Unless you have also configured a local storage backend, the in-container archive files will be deleted after upload. What makes you think they persist locally? Could you share your configuration?

**Comment by m90** [comment]
By mounting your local path to `/archive` , you configure a local storage backend: https://offen.github.io/docker-volume-backup/reference/ thus files are persisted by design.

If you don't want to keep local backups, remove the mount.
