### ISSUE TITLE
Updated email notifications

### ISSUE THREAD

**Issue by danielmbrown603** [offen/docker-volume-backup#41]
I tried googling this one but coming up short. So, I have a special character in my password (#) and its not playing well with the docker composer file. In the previous email notification, I could enclose each entry with quotes but does not seem like I can do that here. Any idea how I could use this method with a password that contains a special character? 

smtp://username:password@host:port/?fromAddress=fromAddress&toAddresses=recipient1

Thank you

**Comment by m90** [comment]
You should be able to do one of three things:

- URL encode your string
- Quote the value. If this creates the same problem as in https://github.com/offen/docker-volume-backup/issues/38#issuecomment-996999726 you need to update Docker/docker-compose: https://github.com/docker/compose/issues/2854
- keep using the old configuration format. Even if it's deprecated, there won't be a new major version unless there is no way around it

**Comment by danielmbrown603** [comment]
How do I URL encode the string? I’m not sure what that means. Can you provide an example?

I’ll update my docker-composer later today and try that too.

Again, thanks for the help. I’m learning a lot.

**Comment by m90** [comment]
URL encoding allows you to use reserved characters in a URL String. Imagine you need to use `&` in the value of a query param. `?value=this&that` will not work (value will be `this`). Instead you encode the `&` like this: `?value=this%26that`. See: https://en.wikipedia.org/wiki/Percent-encoding - the `#` is encoded as `%23`

I don't know which language you use, but it's available in basically every language.

**Comment by danielmbrown603** [comment]
Ok, I think I understand. I’m Just deploying this  as is via docker-compose and trying to configure email notifications.

I’ll try again after I update docker-compose, otherwise I’ll revert back to the legacy email method.

thank you!

**Comment by danielmbrown603** [comment]
I can't figure it out, I'll keep googling. I did upgrade docker-compose and my previous layout doesn't work either. 

The problem I see is I am using a gmail account, so my username contains @gmail.com and my password has a # and & symbol. Seems like docker will not pass those special characters from the env file.

You can close this, its a skillset issue on my part, not an issue with your code. 

Thanks again.

**Comment by m90** [comment]
Maybe you can use this tool to generate your URL: https://github.com/containrrr/shoutrrr/issues/103#issuecomment-749834984

**Comment by danielmbrown603** [comment]
Got it!
I URL encoded my username and password with this https://www.urlencoder.org/
One issue, is I also encoded the ':' between username:password, and that stumped me for awhile. All good now. Thank you
