### ISSUE TITLE
Is there a way to exclude folders or files?

### ISSUE THREAD

**Issue by danielmbrown603** [offen/docker-volume-backup#42]
Is there a way for exclusions? 

For example, I am backing up my Plex library but I'd like to exclude the cache folder because its large and not needed for a restore.

Volume being backed up = dockerapps/plex/:/backup/plex:ro
Exclude = dockerapps/plex/config/Library/Application Support/Plex Media Server/Cache

Thank you

**Comment by m90** [comment]
There is no built in way to exclude certain paths, but you can of course selectively mount certain paths only:

```yml
volumes:
  - /home/app/foo/bar:/backup/foo/bar
  - /home/app/foo/baz:/backup/foo/baz
```

which would omit `/home/app/cache` or similar.

**Comment by m90** [comment]
Also see https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder

**Comment by danielmbrown603** [comment]
> Also see https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder

I tried excluding a folder and that works. Thanks!

**Comment by alexschomb** [comment]
Thanks for the implementation of regex path exclusion in #100 @m90 !

Likely expected and simple question: What's the best solution to multiple exclusions? Such multi variant regular expressions can become really complicated. I suppose that providing an array of expressions is not supported? (yet?)

**Comment by m90** [comment]
@alexschomb If you have a look at the commit history in that PR you can see that I started out having multiple regexes, but I had to drop it for the following reasons:
- the interface for configuring the image is by passing environment variables, this means we can only have a single value for a key (as opposed to for example cli flags, where you could pass `-ignore a -ignore b` and then join them to `[a, b]`)
- if we want to supply multiple values using a single string, we need a delimiter we can split the string on
- [package `envconfig`](https://github.com/kelseyhightower/envconfig) which the image is using for reading configuration from environment variables does so by splitting on commas
- however, commas can also be part of a regex, e.g. `\.{1,5}`
- there's no built in way to escape commas in `envconfig`, i.e. we couldn't support passing regular expressions

There would be a terrible hack that would work like this:
- pass a whitespace separated list of regular expressions
- use a custom non-list type in the config struct
- decode the values into a custom type that behaves like a single regex (i.e. matches the interface), but calls through to the entire list of regexs instead

Considering there is nothing you cannot do with a single regex that you could do with multiple ones (correct me if I'm wrong) and it's just a bit more unwieldy in certain cases (consider `(node_modules|\.git)` which wouldn't be any easier using multiple regexps), I'm not sure if it's worth it? The proper way of allowing for this would probably be using a more sophisticated mode of configuration, although I doubt it's realistic this will happen any time soon.

**Comment by m90** [comment]
It seems spaces can even [be part of a Regular Expression](https://stackoverflow.com/questions/15472764/regular-expression-to-allow-spaces-between-words/15472787#15472787) as well so that hack I described wouldn't work either. I guess we're stuck with a single regex until a different configuration format is supported.

**Comment by alexschomb** [comment]
@m90 Thanks for the detailed explanation. I understand the issue and agree with you that it might not be worth the trouble. My last idea would be implementing this through New-Line-Characters and splitting the string by those. It is highly unlikely that one would use those in his regular expression for selecting filenames/paths. https://github.com/bkeepers/dotenv#multi-line-values
