### ISSUE TITLE
Fail to configure cron schedule

### ISSUE THREAD

**Issue by thematrixdev** [offen/docker-volume-backup#422]
**What are you trying to do?**
Configuring a cron to run at 00:00:00 every day

**What is your current configuration?**
```
environment:
    BACKUP_CRON_EXPRESSION: "0 0 0 * * *"
```

**Log output**
```
time=2024-05-23T09:08:10.488Z level=INFO msg="Successfully scheduled backup from environment with expression 0 0 0 * * *"
time=2024-05-23T09:08:10.495Z level=WARN msg="Scheduled cron expression 0 0 0 * * * will never run, is this intentional?"
```

**Additional context**
According to this page
https://offen.github.io/docker-volume-backup/reference/
`0 0 0 * * *` should mean 00:00:00 every day, right?

**Comment by m90** [comment]
This is maybe a bit misleading, but when used, the seconds field is not the first item in the expression: https://pkg.go.dev/github.com/robfig/cron/v3

In your particular case, I don't see a reason to use seconds at all though, and would just opt for `0 0 * * *` which will be the most portable cron schedule.

**Comment by thematrixdev** [comment]
> This is maybe a bit misleading, but when used, the seconds field is not the first item in the expression: https://pkg.go.dev/github.com/robfig/cron/v3
> 
> In your particular case, I don't see a reason to use seconds at all though, and would just opt for `0 0 * * *` which will be the most portable cron schedule.

So it should be like Linux cron:
```
# m h  dom mon dow
```

**Comment by m90** [comment]
As stated in the table, the seconds field is optional. If you use 5 fields, it's standard Linux cron behavior, yes.
