### ISSUE TITLE
Empty directories are not copied

### ISSUE THREAD

**Issue by MarkoArsic** [offen/docker-volume-backup#43]
Why this backup does not copy empty directories, or am i missing something.
I cannot start containers..
Thank you

**Comment by m90** [comment]
This would need to be fixed upstream, either in https://github.com/walle/targz or https://github.com/m90/targz

**Comment by m90** [comment]
A fix for this is included in [v2.7.2](https://github.com/offen/docker-volume-backup/releases/tag/v2.7.2)

**Comment by MarkoArsic** [comment]
Thank you, that was quick!!

**Comment by m90** [comment]
To be fair, the build is still running, so the Docker image tag will be available in 10 minutes or so.

**Comment by MarkoArsic** [comment]
Btw, great container, only thing that is missing is ssh, remote backup ,hope you can build this feature in future...

**Comment by m90** [comment]
> only thing that is missing is ssh

I don't really need this feature myself (I'm doing remote backups against MinIO) but I wouldn't be opposed to merging a PR that adds it. Feel free to open a PR or add an issue so that others might pick it up.
