### ISSUE TITLE
Azure storage: Support access tier

### ISSUE THREAD

**Issue by LarsWesselius** [offen/docker-volume-backup#433]
It would be great if the access tier could be specified in the config of the blobs uploaded. Now, they get uploaded with whatever is the default of the storage account.

If you pass a [UploadStreamOptions](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob@v1.3.2/blockblob#UploadStreamOptions) into `UploadStream` here:
https://github.com/offen/docker-volume-backup/blob/bb11ae035b4d563f7fe86e9bcb7e3dac3c29ed4f/internal/storage/azure/azure.go#L106
You can specify the access tier. For most usecases, you'd probably want Archive.

I would make a PR but I will not pretend to understand how Go works.

**Comment by m90** [comment]
I'm happy to merge a PR that adds this, if it's useful for people.

I won't really have much time to add it rather soon, but do not feel scared, this repo has seen quite a few contributions from people who haven't used Go before, so I would think you'll definitely have what it takes to add it. This PR (adding S3 storage classes) might help as a guideline #119

**Comment by m90** [comment]
This is now supported as of [v2.41.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.41.0)
