### ISSUE TITLE
[FR] upgrade `shoutrrr` to v0.8.0 to support custom fields in calls to Generic Webhooks

### ISSUE THREAD

**Issue by huyz** [offen/docker-volume-backup#447]
**Is your feature request related to a problem? Please describe.**

I have notifications sent to a Generic Webhook endpoint. But I'm in need of fields other than `title` and `message` to be sent.

**Describe the solution you'd like**

In order to support https://containrrr.dev/shoutrrr/dev/services/generic/#custom_data_fields , please bump the shoutrrr dependency to v0.8.0 to benefit from these commits: https://github.com/containrrr/shoutrrr/pull/377

**Describe alternatives you've considered**

I current use hacks to inject data in the `title` and `message` fields and have to do special processing to extract that data.

**Comment by m90** [comment]
Happy to merge and release a PR that updates this, in case anyone wants to do it.

**Comment by huyz** [comment]
Thanks @m90 !

**Comment by m90** [comment]
This is now included in [v2.40.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.40.0)
