### ISSUE TITLE
Pre/Post backup routine scripts

### ISSUE THREAD

**Issue by danielmbrown603** [offen/docker-volume-backup#45]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* **What is the current behavior?**
* No ability to reference pre and post backup scripts

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
Ability to reference scripts as part of the backup routine. For example, I could reference a database script to create a backup and then have docker-volume-backup tool backup the flat file, and all while leaving the database running. Or pihole is also the current use case I have as I don't want to take it down if I don't have too. Referencing a simple custom pre-backup script could solve this. 

```
#!/bin/sh
# This script will create a Teleport backup to a directory that it is run in.

# Change to mapped directory
cd /backup

# Run Backup
pihole -a -t &

# Record the process id and wait
process_id=$!
wait $process_id
echo "Backup complete with status $?"
```

* **Please tell us about your environment:**
  
  - Image version:latest
  - Docker version: 20.10.12
  - docker-compose version: 1.29.2

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by m90** [comment]
This is a good idea, but also pretty tricky to implement.

Mounting a script into the backup container and running it on certain occasions would be very simple, but won't be of much help as you likely want to run these scripts _inside the application containers_. This could be done using labels containing a command on the application containers, but that creates a few other obstacles:

- replicating the behavior of `docker exec` using the Docker client is _ridiculously_ hard, I failed to get it working once (it should be possible though)
- this setup also gets tricky once you have multiple backup containers running in a setup: which backup container is supposed to trigger which commands? This probably could work like the `stop-label` mechanism, but I haven't thought it through entirely.

Considering this feature would take quite some time to implement and I don't need it myself I probably won't implement it too soon (there are other missing features like #29 that I would be using myself). If anyone wants to work on this though I am happy to give advice and merge PRs.

**Comment by m90** [comment]
I started working on this here https://github.com/offen/docker-volume-backup/tree/exec-commands

**Comment by m90** [comment]
This is now supported as of [v2.13.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.13.0).
