### ISSUE TITLE
[Feature] Allow BACKUP_COMPRESSION to be disabled

### ISSUE THREAD

**Issue by jzebedee** [offen/docker-volume-backup#455]
I'd like to be able to create uncompressed backup archives as plain old `.tar`s. It looks like [getCompressionWriter](https://github.com/offen/docker-volume-backup/blob/main/cmd/backup/archive.go#L94) doesn't support disabling compression and the app always [defaults to gzip compression](https://github.com/offen/docker-volume-backup/blob/main/cmd/backup/config.go#L32).

**Comment by m90** [comment]
If you wanna add a `none` compression type that just passes through the tar file, I am happy to merge and release a PR for that.

**Comment by m90** [comment]
This is now supported as of [v2.42.0](https://github.com/offen/docker-volume-backup/releases/tag/v2.42.0)
