### ISSUE TITLE
Email is not sent

### ISSUE THREAD

**Issue by MarkoArsic** [offen/docker-volume-backup#46]
* **I'm submitting a ...**
  * support request

* **Please tell us about your environment:**
  
  - Image version: 2.7.2
  - Docker version:  20.10.11
  - docker-compose version: v2

Hello,
can you please help me with email notifications,
Everything is working great, but email is not sent.
I triggerd a **manual backup** with docker exec <container_id> backup, the containers are all down, tar was created but email is not sent...

Here is the compose part for backup

  backup:
        restart: always
        profiles: ["backup"] 
        image: offen/docker-volume-backup:v2.7.2
        hostname: dzgz
        environment:
            - BACKUP_FILENAME=backup-%Y-%m-%dT%H-%M-%S.tar.gz
            - BACKUP_LATEST_SYMLINK=backup.latest.tar.gz.gpg
            - BACKUP_RETENTION_DAYS=2
            - BACKUP_PRUNING_LEEWAY=5m
            - BACKUP_PRUNING_PREFIX=backup-
            - BACKUP_CRON_EXPRESSION=0 19 * * 1-5
            - NOTIFICATION_URLS=smtp://prefix%5Ctest1@example.com:passwd@domainurl:25/?fromAddress=test1@example.com&toAddresses=test2@example.com
            - NOTIFICATION_LEVEL=info
        volumes:
            - solar-data:/backup/solar-data:ro
            - solar-solrhome:/backup/solar-solrhome:ro
            - alf-data:/backup/alf-data:ro
            - postgres-data:/backup/postgres-data:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./backups:/archive  
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro   

*%5C in URL refers to the \

SMTP SERVER IS WORKING WELL , i send email via telnet like this:

C: MAIL FROM:<test1@example.com>
C: RCPT TO:<test2@example.com>
C: DATA
C: From: "Pisarnica" <test1@example.com>
C: To: "Test1" <test2@example.com>
C: Date: Wed, 05 Jan 2022 14:40:00 +0100
C: Subject: Test message
C: Hello Alice.
C: This is a test message with 5 header fields and 4 lines in the message body.
C: Your friend,
C: Bob
C: .

In this telnet example there is no username and pass, so i cut that part from the URL
        - NOTIFICATION_URLS=smtp://domainurl:25/?fromAddress=test1@example.com&toAddresses=test2@example.com
..there was no errors but email still was not sent..

I could not do any troubleshooting cause there is no outputs to the console about emails from the container .

Do you have any clue of what is going on here..
Thank you very much!

**Comment by m90** [comment]
Your configuration as is looks correct and I'm using email notifications in the very same manner myself, so it's probably about that URL itself.

> I could not do any troubleshooting cause there is no outputs to the console about emails from the container .

In case sending the email returns an error you should see a message like this in your log output:

```
Backup procedure ran successfully, but an error ocurred calling the registered hooks: ...
```

In case this is not present it means that the email client is able to send out the notification, but it's likely not being sent to the correct address.

I'm not entirely sure about the meaning of that double backslash in your email. Could you maybe try using this tool https://github.com/containrrr/shoutrrr/issues/103#issuecomment-749834984 to encode the URL and see if it produces the same result?

**Comment by MarkoArsic** [comment]
Thanks for the quick response!
i will try that

**Comment by MarkoArsic** [comment]
Actually, this param: BACKUP_PRUNING_LEEWAY=5m, block me of viewing the error log (i didn't wait 5 min ),  error msg shows after 5min of sleep :-)

I got this error without touching the previous setup, then i replace all @ signs with %40 in username, fromAddress and toAddress, did not replace @ prefix to the hostname. Also in username i have a prefix to a username in form of a backslash (\) which replaced with %5C. 

`- NOTIFICATION_URLS=smtp://prefix%5Cusername%40example.com:PassWd@hostname:port/?fromAddress=username@example.com&toAddresses=test1@example.com`

Every try resulted with same error >

`level=error msg="Backup procedure ran successfully, but an error occurred calling the registered hooks: runHooks: error running hook: notifySuccess: error notifying: sendNotification: error sending message: error enabling StartTLS: x509: cannot validate certificate for 172.20.0.40 because it doesn't contain any IP SANs"`

Is TLS/SSL security necessary? 

I'm already sending emails from Spring Boot to that server with just following setup (no SSL/TLS, just simple smtp auth) 
spring.mail.host=hostIpAddress
spring.mail.port=25
spring.mail.username=prefix\username@example.com
spring.mail.password=PaSswD
# Other properties
spring.mail.properties.mail.smtp.auth=true

Thanks!!

**Comment by m90** [comment]
Reading this: https://containrrr.dev/shoutrrr/v0.5/services/email/ I think passing `useStartTLS=no` might work for you but I'm not sure about other options that need to be set. In any case you should be able to get the setup you need using the parameters described in the `shoutrrr` documentation.

**Comment by MarkoArsic** [comment]
Finally! 
got thiis working, here [](https://containrrr.dev/shoutrrr/v0.5/services/email/)  they said the key is: **useStartTLS**, but it is actually a **StartTLS**. beside that i added two more : auth=None&encryption=None
And it is working!
Thank you very much for the assistance !!

**Comment by MarkoArsic** [comment]
We can successfully  close this assistance!
