### ISSUE TITLE
Send notifications via SSH to another desktop / notify-send (and more)

### ISSUE THREAD

**Issue by robincee** [offen/docker-volume-backup#465]
Looking at the code & docs at https://offen.github.io/docker-volume-backup/how-tos/set-up-notifications.html and https://containrrr.dev/shoutrrr/v0.8/ i figured: Would it be an idea to implement support for notify-send over SSH? eg:

`ssh user@host 'DISPLAY=:0 notify-send "Backup Success!"'`

Could be something like this inside the compose.yml:

`NOTIFICATION_SSH=ssh://user@host:port/?display=0&fromHost=example.com`

Thank you folks for a great piece of work!

**Comment by m90** [comment]
I think it wouldn't make sense for this tool to add an additional way of sending notifications through other means than the library used, `shoutrrr`, so if a channel like notify-send is currently not supported by `shoutrrr`, the way to go would be to request its addition (or add it yourself) [there](https://github.com/containrrr/shoutrrr/issues) and once merged, bump the library version here (which happens quite regularly, e.g. #212, #447)

**Comment by m90** [comment]
In the meantime, you could probably also implement something similar using custom commands, as for example described here https://github.com/offen/docker-volume-backup/issues/159

**Comment by robincee** [comment]
Thank you for the information! Apologies: i discovered shoutrrr right after i posted this. Already figured the same. I'll do one better: i got working code now in Go (just started with Golang due to this lol, but looks doable), working on a patch for DVB, so i can patch my local version until / when / if ever shoutrrr accepts a (future) pr after i get into that code and figure out how to implement it there (lots to learn!) And i hope shoutrrr will accept it, cause SSH is 'something else'. + Totally understand what your are saying, fully agreed. TBC!

For now a simple bit like this seems to work great with openssh added via the Dockerfile.
```
    if s.c.SSHNotificationUrl != "" && s.c.SSHNotificationString != "" {
        cmd := exec.Command("ssh", fmt.Sprintf("%s", s.c.SSHNotificationUrl), fmt.Sprintf("%s", s.c.SSHNotificationString)+" 'Backups FAILED.'")
        cmd.Run()
    }
```
Thanks again!

**Comment by m90** [comment]
You wouldn't even need to patch the code for the image but could put the command you exec in a `copy-post` command on your backup container. See #159 and #297
