### ISSUE TITLE
Support Nextcloud / WebDav

### ISSUE THREAD

**Issue by Kaerbr** [offen/docker-volume-backup#47]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**  
I see no ability to sync my backups to Nextcloud (Webdav).

* ~~**If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**~~

* **What is the expected behavior?**  
I would like to sync the backups to a specific folder inside my Nextcloud (I guess webdav would be the protocol?!).

* **What is the motivation / use case for changing the behavior?**  
 I could use a tool like [rclone](https://rclone.org/) but it would be way easier to set some env variables (eg.: source_folder, dest_folder, username, password/token). Just like its possible to sync to S3.

* **Please tell us about your environment:**
  - Image version: v2.7.2
  - Docker version: Docker version 20.10.12, build e91ed57
  - docker-compose version: ---

* ~~**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)~~

**Comment by m90** [comment]
I personally do not have any experience with either WebDAV or Nextcloud, but in case someone wants to implement it as a backup target, I would be happy to merge PRs and help with implementing. It seems WebDAV is supported by the Go standard library already: https://pkg.go.dev/golang.org/x/net/webdav so it's probably not too big of a task. Anyone interested could probably start looking at what happens in `(*script).copyBackup()` and add another block that uploads via WebDAV in case it's configured.

**Comment by Kaerbr** [comment]
Thanks for the quick response! (:

I myself have no expirience in go but I'll have a look when I find time. 👍🏼

**Comment by m90** [comment]
> I myself have no expirience in go but I'll have a look when I find time.

Great, let me know if I can provide guidance here.

**Comment by m90** [comment]
Oh, I just noticed package `webdav` from the stdlib is a server when we need a client. We'd probably need to use this https://github.com/studio-b12/gowebdav#upload-file-via-writer instead then.
