### ISSUE TITLE
Would it be possible to support Google Drive

### ISSUE THREAD

**Issue by dustin-auby** [offen/docker-volume-backup#471]
Hi, would it be possible to use google drive or event a google storage bucket. we only use google services and at the moment have no way to implement this.

**Comment by m90** [comment]
Google Cloud Storage does support the S3 protocol, so you can definitely use it as a backend for this tool using the S3 configuration: https://cloud.google.com/storage/docs/interoperability

As for Google Drive, I'd think it's probably possible but also complicated to an extent where I'm not sure it's worth it. This has also been discussed here #103

**Comment by luizguilhermesj** [comment]
I created a script for Google Drive upload and retention (totally inspired by docker-volume-backup) 
I pushed it into an image on:
https://hub.docker.com/r/luizguilhermesj/docker-volume-google-drive-backup

I created it this afternoon using my free quota of http://cursor.com/
I have no previous experience with go, so don't shame me please 😅 

context: I got lockedout of my azure account, so I needed to rush into a solution to backup my stuff elsewhere and I do have a lot of space on Google Drive.
So the script doesn't even have tests, I'll try to improve it moving forward.
And I do see the pain it would be to support an integration with it.

**Comment by m90** [comment]
@luizguilhermesj if you feel like wrangling cursor into writing a Google Drive backend that can be used in addition to what already exists, I'd be happy to merge it. From a brief look at the code it looks it should be possible.
