### ISSUE TITLE
Random failure with tar error "write too long"

### ISSUE THREAD

**Issue by bazsodombiandras** [offen/docker-volume-backup#503]
**Describe the bug**
I'm running multiple Docker volume backups with the same schedule, at 3AM (simultaneously). Some of these volumes are fairly large in size (>500 MB). The backup randomly fails with an error message from tar, saying "write too long".

A sample error message look like this:
```
time=2024-12-10T03:00:00.061+02:00 level=INFO msg="Stopping 1 out of 27 running container(s) as they were labeled docker-volume-backup.stop-during-backup=home-assistant."
time=2024-12-10T03:00:15.865+02:00 level=INFO msg="Restarted 1 container(s)."
time=2024-12-10T03:00:15.866+02:00 level=INFO msg="Removed tar file `/tmp/home-assistant-daily-2024-12-10T21-11-00.tar.gz`."
```

The random failure happens both with large volumes and small volumes.
The random failure happens both for volumes of containers which are automatically stopped and for volumes of containers that are not automatically stopped.
It happens roughly once in 3 days, for at least one volume, sometimes multiple volumes.

**To Reproduce**
Run the backup multiple times until it fails.

**Expected behavior**
No failure.

**Version (please complete the following information):**
 - Image Version: v2.43.0 (was the same in older versions too)
 - Docker Version: v27.3.1
 - Docker Compose Version (if applicable): v2.29.7

**Comment by m90** [comment]
This usually happens when the contents of your volume are changing while the archive is being created, see: https://github.com/offen/docker-volume-backup/issues/106

Ideally, you stop all consumers during backup creation, or you create the backup from a snapshot, see: https://offen.github.io/docker-volume-backup/how-tos/replace-deprecated-backup-from-snapshot.html

**Comment by bazsodombiandras** [comment]
Thank you!
