### ISSUE TITLE
Saving a backup to a subdirectory of a AWS-S3-Bucket

### ISSUE THREAD

**Issue by abCobby** [offen/docker-volume-backup#51]
First of all, I would like to say that this is a great image. However, I want to save my backup in a subdirectory, but I can't find any configuration option. Could someone help me? Maybe I am missing something.

**Comment by m90** [comment]
I thought this was supported by prefixing your `BACKUP_FILENAME` with a directory name but it seems this gets eaten here: https://github.com/offen/docker-volume-backup/blob/1db896f7cfc44eeb06a24d7f2f98496a4fd35d65/cmd/backup/main.go#L526

Not sure if this is to be considered a bug or intended behavior right now though as users might have started to rely on that behavior.

Maybe the easiest thing to do would be to model this like it's done with WebDAV backends, where you supply `WEBDAV_PATH` which then gets prefixed before uploading. So you'd provide `AWS_S3_PATH` and this is used for all uploads if given.

I personally don't need this and won't have the time to implement it soon, but in case someone wants to pick it up I'm happy to review and merge PRs, it should be a simple thing to get done.

**Comment by abCobby** [comment]
Thanks for the quick feedback. However, I will unfortunately not manage to implement it either. We will use the image anyway.

**Comment by m90** [comment]
You can now do this after updating to `v2.9.0` and setting `AWS_S3_PATH`. Refer to the updated README for further info.

**Comment by abCobby** [comment]
Thank you very much. Now the image is even more awesome.
