### ISSUE TITLE
Confusing README.md "Restoring..." section example

### ISSUE THREAD

**Issue by Fridgemagnet** [offen/docker-volume-backup#55]
Hi Mr Offen,

this is not so much an issue but more of a suggestion so as to avoid confusion when reading through the example part of the restore section:

Not having the same name for the container and the mounted restore volume. Both are currently "backup_restore" and although I understood it I found it quite confusing at first.

docker run -d --name **_temp_restore_container_** -v data:/backup_restore alpine
docker cp /tmp/backup/data-backup **_temp_restore_container_**:/backup_restore
docker stop **_temp_restore_container_**
docker rm **_temp_restore_container_**

**Comment by m90** [comment]
Fair point. Wanna open a PR that uses the names you provided in the example? I do like the `temp_restore_container` name as it's pretty explicit about what the thing is supposed to do. Thank you!

**Comment by Fridgemagnet** [comment]
Done. First pull request, yay. ^^
Woah... Being able to see the CircleCI processes run is pretty damn cool!
