### ISSUE TITLE
Case sensitivity of "docker-volume-backup.stop-during-backup" value causing compose v3 labels to not stop containers ("True" vs "true")

### ISSUE THREAD

**Issue by Fridgemagnet** [offen/docker-volume-backup#57]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
Despite the  "docker-volume-backup.stop-during-backup" label being set to "True", multiple docker containers are not stopped during the backup process.

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**
When a portainer stack uses docker compose version 3 in the yaml file the environment variable for  "docker-volume-backup.stop-during-backup" is set to "True" (upper case "T") even though it was written as follows (notice the lower case "t" used for "true"):
```
labels:
  docker-volume-backup.stop-during-backup: true
```

This causes the the docker-volume-backup container to not stop the desired containers.

* **What is the expected behavior?**
The correct stop behaviour regardless of the docker compose version used.

* **What is the motivation / use case for changing the behavior?**
Ease of use and to fix a bug.

* **Please tell us about your environment:**
  
  - Image version: latest (as of 5th Feb 2022)
  - Docker version: 20.10.12, build e91ed57
  - docker-compose version: 1.29.2, build 5becea4c

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

Problem can be solved by using the compose v2 format even if the stack uses v3:
```
    labels:
      - docker-volume-backup.stop-during-backup=true
```

**Comment by m90** [comment]
Thanks for submitting this. I'm not entirely sure if I'd feel ok with just making the check case-insensitive as people might (potentially unknowingly) rely on this behavior when defining a non-default value and things start behaving differently after an update. The docs also tell you to use `docker-volume-backup.stop-during-backup=true` which, as far as I understand works as intended in all compose versions. 

I think I'll try to repro this in v2/v3 compose and add a note to the docs about this behavior.

**Comment by Fridgemagnet** [comment]
Just did some more research and apparently this is standard docker compose behaviour if it is not enclosed in quotation marks.
From the "Compose file version 3 reference":

> Add environment variables. You can use either an array or a dictionary. Any boolean values (true, false, yes, no) need to be enclosed in quotes to ensure they are not converted to True or False by the YML parser.

I'll close the issue as there is nothing wrong with the docker-volume-backup image. :)
