### ISSUE TITLE
Support scp backed storage

### ISSUE THREAD

**Issue by m90** [offen/docker-volume-backup#65]
Given the current architecture of this script, it would be relatively easy to add support for storing backups on remote systems that are accessed by SSH / `scp`.

Open questions:
- how does pruning of old backups work in this scenario? `scp` itself does only copy. Is there another suitable Go library for syncing files over the wire?
- how does authentication work? Do users mount authorized SSH keys into the container? Are there any security issues I am not aware of?

**Comment by rpatel3001** [comment]
a better idea might be supporting rclone and having users mount an rclone.conf file. instant support for a ton of backends

**Comment by rpatel3001** [comment]
Nope, go was too much trouble. A couple hiccups but I hooked up my shell script that syncs my latest backup using rclone to be triggered once a backup job has run. 

Add to the backup container itself:
```
    labels:
      - docker-volume-backup.exec-post=/bin/sh -c '/sync/setup.sh'
    volumes:
      - ./config/sync_backup:/sync:ro
```

And the contents of `./config/sync_backup`:
32 bit `rclone` executable
32 bit `shoutrrr` executable
`rclone.conf`, generated by running `rclone config --config ./config/sync_backup/rclone.conf`
any other files required by rclone (key files for remotes)

`setup.sh`:
```
#!/bin/sh
apk add --update openssh-client at
atd
# need to run the sync after the backups have been rotated and the symlink updated
echo /sync/sync_backup.sh | at now +10 minutes
```

`sync_backup.sh`:
```
#!/bin/sh

# I'm using a single URL, this might not work with multiple
CMD="send -u $NOTIFICATION_URLS"

# tell me how big each of my volumes, mounted as folders under /backup, takes up
/sync/shoutrrr $CMD -t "Backed up volume sizes" -m "`du -sm /backup/* | sort -rg | sed 's#/backup/##' | sed 's#\([0-9]\+\)#\1M#'`"

counter=0
# measure how long the upload takes
START_TIME=`date +%s`
echo "Uploading to Google Drive"
until
   /sync/rclone copy --config /sync/rclone.conf -vL /archive/backup-latest.tar.gz gdrive:
do
   sleep 1
   [ "$counter" -eq "$max_retry" ] && echo "Failed!" && break
   echo "Trying again. Try #$counter"
   counter=$((counter+1))
   /sync/shoutrrr $CMD -t "Backup sync" -m "google drive upload failed on iteration $counter/$max_retry"
done
END_TIME=`date +%s`
/sync/shoutrrr $CMD -t "Backup sync" -m "google drive upload took $((($END_TIME-$START_TIME)/60)) min"

counter=0
START_TIME=`date +%s`
echo "Uploading to VPS"
until
   /sync/rclone copy --config /sync/rclone.conf -vL /archive/backup-latest.tar.gz vps:backup
do
   sleep 1
   [ "$counter" -eq "$max_retry" ] && echo "Failed!" && break
   echo "Trying again. Try #$counter"
   counter=$((counter+1))
   /sync/shoutrrr $CMD -t "Backup sync" -m "vps upload failed on iteration $counter/$max_retry"
done
END_TIME=`date +%s`
/sync/shoutrrr $CMD -t "Backup sync" -m "vps upload took $((($END_TIME-$START_TIME)/60)) min"
```

**Comment by m90** [comment]
Thanks for sharing this. Considering that a small image size is a key design goal of this image, it would be ideal if we could be using something here that is available as a native Go package. Installing other software in the image and then calling through should probably not happen.

Then again people who want to do something like this could also use the image as a base for their own image, triggering pre/post scripts. I'll need to think about this a little.

**Comment by rpatel3001** [comment]
Yeah it's definitely a hack. Rclone is written in go and can probably replace all the other backends that are currently available. I tried importing it as a package but apparently it only supports being built as an executable, but maybe someone who knows go can figure it out.

**Comment by m90** [comment]
Seems using rclone from within Go code is possible but not officially supported (i.e. no API stability and such): https://forum.rclone.org/t/rclone-as-a-golang-module-or-other-way-of-using-it-in-code/17172

**Comment by rpatel3001** [comment]
Did an experiment with adding rclone. Installing via apk or copying it in from the rclone/rclone image both grow the compressed size from 14 MB to 25 MB on my machine. Some of that may be offset by removing various go modules that rclone would replace. 

Building and copying in the shoutrrr binary adds 5 more MB. 

Incidentally, changing `--update` to `--no-cache` reduces the compressed size from 14 MB to 12 MB.

**Comment by m90** [comment]
> Incidentally, changing --update to --no-cache reduces the compressed size from 14 MB to 12 MB.

Oh this is a nice find, I am surprised the install didn't use `--no-cache` yet. I changed this in 5ec2b2c3ffcd793a6dbf0246b7acf8077457e1fb and will include it in the next release. Thanks for mentioning.

> It would also be nice to have a feature to send shoutrrr notifications with stats on backup uploads.

The image as is using `shoutrrr` to send notifications already https://github.com/offen/docker-volume-backup#send-email-notifications-on-failed-backup-runs - is there anything you would like to do, but cannot do using that feature?

About replacing literally _everything_ with rclone I am a little skeptical as this might make sense but is a very big undertaking that brings a lot of compatibility issues when adding it to the existing image. If there will ever be a  v3 it might be worth considering, but as long as this image stays a v2, it's probably too complex to support.

**Comment by rpatel3001** [comment]
Stats about the upload would be like how long it took (separate from the rest of the process) and how many bytes were sent if that can be parsed from the output. It's moot for me since I'm not using the built in backends anyway. 

>If there will ever be a v3 it might be worth considering, but as long as this image stays a v2, it's probably too complex to support.

Makes sense, and my little hack is functional enough for now.
