### ISSUE TITLE
docker permissions

### ISSUE THREAD

**Issue by rpatel3001** [offen/docker-volume-backup#68]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**
There is no documentation of which docker permissions are required.

* **What is the motivation / use case for changing the behavior?**
I'm wary of giving containers unrestricted access to the docker socket and would like to expose it via docker-socket-proxy and the DOCKER_HOST environment variable with limited permissions.

**Comment by m90** [comment]
Two things about this:

Using `DOCKER_HOST` is currently not supported. It should be though so I openend an issue to track this #69 

I have never used `docker-socket-proxy` so I am not sure about how exactly configuring it would work in this context. It definitely needs `CONTAINER` and `SERVICE`, it will also need `POST` but I cannot tell you what else is required.

**Comment by m90** [comment]
Using `DOCKER_HOST` is now supported as of `v2.12.0`.

**Comment by rpatel3001** [comment]
It works, thanks. I'm not using swarm so it works with just POST and CONTAINERS.
