### ISSUE TITLE
Restore instructions are unnecessarily complicated

### ISSUE THREAD

**Issue by m90** [offen/docker-volume-backup#75]
May I suggest an easier instruction to restore on the README?
It just seems unnecessarily complicated. Also it doesn't tell to remove the volume first, which can be a problem if the volume already exists.

This is what I propose:

`docker volume rm volume_name` # this removes volume if it exists

`docker run --rm -it -v volume_name:/backup/my-app-backup -v /path/to/local_backups:/archive:ro alpine tar -xvzf /archive/full_filename.tar.gz` # this creates volume first

_Originally posted by @kzshantonu in https://github.com/offen/docker-volume-backup/issues/71#issuecomment-1047335069_

**Comment by m90** [comment]
About your suggestion: I'm not entirely sure why you would need / want to remove the volume? From what I understand you should be able to keep the existing volume and replace its contents with the untared archive?

**Comment by kzshantonu** [comment]
The example extracts an archive directly into a volume and overwriting data, which can cause problems if for example it's a database volume. Instead of resulting in a database that you know works (eg: last night's backup), you end up with good files mixed with stale and possibly corrupted files (if someone's restoring to recover from corruption)

**Comment by m90** [comment]
Hmm, I see what you mean. Then again there is probably no one size fits all approach and I have to admit I would be afraid to advise people to remove the volume by default (looking at the config examples posted in the issues here there are lots of different approaches taken, people for example add compose files and such to the backup).

Maybe it'd be a good idea to structure the docs with some possible restoration scenarios and explain the pros and cons of each in detail. What do you think?

**Comment by kzshantonu** [comment]
Agreed. I guess the doc could suggest to trigger a manual backup first, then restoring a `snapshot`. The word is key. Or have two scenarios of `snapshots` and overwriting

**Comment by m90** [comment]
Sounds good. I'll try to add this when time allows (unless you would like to join here, which would also be much appreciated). Thanks for your input!

**Comment by kzshantonu** [comment]
Anytime. Will submit a PR in sometime
