### ISSUE TITLE
PaxHeaders.0 throughout my tar file

### ISSUE THREAD

**Issue by danielmbrown603** [offen/docker-volume-backup#88]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **What is the current behavior?**
In every folder, there is a "PaxHeaders.0" folder that duplicate files from the original folder.
foobar.app/foobar files
foobar.app/PaxHeaders.0/foobar files

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**
The container runs fine on my Ubuntu server but this PaxHeaders.0 issue occurs on my synology running the same container and same env. The synology has the latest synology updates. DS1821+.

* **What is the expected behavior?**
No PaxHeaders.0. Is there a way to exclude this somehow? Its in every folder that I backup.
* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Image version: 2.15
  - Docker version: Latest supported on the synology
docker version
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.13
 Git commit:        b455053
 Built:             Thu Aug 19 07:13:24 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.13
  Git commit:       a3bc36f
  Built:            Thu Aug 19 07:11:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00

  - docker-compose version: Latest supported on the synology

docker-compose version
docker-compose version 1.28.5, build 324b023a
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, etc)

**Comment by m90** [comment]
How do you untar the archive?

**Comment by m90** [comment]
Any input on this @danielmbrown603? To expand on my question: Pax Header files are expected to be in the archive in certain cases (Go will selectively pick a header format based on the current requirements for writing file info) but they should not be part of the untared content.

This is what package `tar` says:
```
	// If the format is unspecified when Writer.WriteHeader is called,
	// then it uses the first format (in the order of USTAR, PAX, GNU)
	// capable of encoding this Header (see Format).
	Format Format
```
which makes me think the Synology files cannot be written to `USTAR` header and are using `PAX` format instead, but for whatever reason these will be interpreted as actual files when you untar the archive. To me this sounds as if there's a mismatch between the way Go writes tar headers and the way your untar mechanism treats these headers. Do you use plain Linux/MacOS `tar` to do this or are you using something else? Could you provide an archive that lets me reproduce the behavior?

**Comment by danielmbrown603** [comment]
@m90 Sorry, busy week.
I just started using this with synology, so I haven't untar'd anything yet. 
I'm using what comes with the container and synology. 

I'll message you a link to download the tar.

**Comment by m90** [comment]
The file you sent to me does not contain any header files when I inspect in on my machine:

`´´
➜  untar tar -xvf san2-2022-04-03T12-58-46.tar.gz 
tar: Entferne führende „/“ von Elementnamen
/backup
/backup/offen
/backup/offen/notifications
/backup/offen/notifications/notifications.tmpl
➜  untar tree backup 
backup
└── offen
    └── notifications
        └── notifications.tmpl
```

>  so I haven't untar'd anything yet

How do you know the archive contains such extraneous files then?

**Comment by danielmbrown603** [comment]
Interesting. I opened up the file with 7zip, that is how I saw the PaxHeaders.

![image](https://user-images.githubusercontent.com/79930376/161444023-80abc987-2c4d-4b52-bbde-8ede489532b3.png)

![image](https://user-images.githubusercontent.com/79930376/161444162-b306ed28-1be2-44fb-ae36-758f1ba5d791.png)

Hmm

**Comment by m90** [comment]
Seems this is a limitation of 7zip and it doesn't know about PAX headers so it treats them as files. Is there another common way of extracting tar files on Windows? Does it produce the same output?

It would definitely be possible to add a `UstarHeadersOnly` config option or similar that makes sure the archive does not use Pax Headers ever, but then I am not entirely sure if a. it's worth it and b. it has other unintended consequences.

**Comment by danielmbrown603** [comment]
Good insight. Ok, so I replicated the exact backup but from Ubuntu 20.04.4 LTS running my other docker containers. I also opened it the exact same method with 7zip and listed the contents as shown below. What do you think is going on? Although its a new Synology running the latest software, maybe Synology lags behind in some of the linux packages? 

![image](https://user-images.githubusercontent.com/79930376/161444832-b93a064f-6061-4431-bd89-fcde0f4e50ee.png)

![image](https://user-images.githubusercontent.com/79930376/161444917-8be8faff-3ec1-4018-8dee-edee101ebe6f.png)

**Comment by m90** [comment]
I'm not entirely sure when that happens exactly, but it seems Go will selectively choose which header format to use:

```
	// If the format is unspecified when Writer.WriteHeader is called,
	// then it uses the first format (in the order of USTAR, PAX, GNU)
	// capable of encoding this Header (see Format).
	Format Format
```

Something must make the Synology setup choose the PAX format when your Ubuntu setup can use USTAR format for the same content. The code choosing this lives here https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/archive/tar/common.go;l=333-412;drc=refs%2Ftags%2Fgo1.18 but right now I don't really have a good explanation for the behavior you are seeing.

**Comment by m90** [comment]
Knowing where those files are coming from, are you able to use the archives on Windows without having to wrangle the header files or should we look into adding a "WindowsCompatibleArchive" (or a better name) option @danielmbrown603

**Comment by danielmbrown603** [comment]
That could definitely work but is there some way to add an exclusion option? Although different but with rclone, I have a section that I can exclude folders. This exclusion is regardless of the actual path. It's something like this. 

	--exclude *fuse_hidden*
	--exclude *_HIDDEN
	--exclude .recycle**
	--exclude .Recycle.Bin/**
	--exclude *.backup~*
	--exclude *.partial~*

**Comment by m90** [comment]
The only way to exclude files is currently the one described in #42, globbing or similar is not supported at the moment.

**Comment by danielmbrown603** [comment]
That's right, ok.

Do you want to try WindowsCompatibleArchive? I'm more than happy to test.

**Comment by m90** [comment]
This is not hard to implement, but I need to think about the best API for this a little further (this could either be Windows-focused or expose tar options). I'll think about this for a little while. When I come up with something that feels solid, I'll circle back here.

**Comment by m90** [comment]
@danielmbrown603 When you find the time, could you try building an image from the [header-format](https://github.com/offen/docker-volume-backup/tree/header-format) branch:

```
git clone git@github.com:offen/docker-volume-backup.git
cd docker-volume-backup
git checkout header-format
docker build . -t offen/docker-volume-backup:header-format
```
and then try running a backup using the `offen/docker-volume-backup:header-format` image while setting `TAR_ARCHIVE_HEADER_FORMAT="USTAR"` and see if it would still contain the header files when unzipped using 7zip?

**Comment by danielmbrown603** [comment]
$ git clone git@github.com:offen/docker-volume-backup.git
Cloning into 'docker-volume-backup'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by m90** [comment]
See https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#make-sure-you-have-a-key-that-is-being-used or you could also use a https URL to clone the repo if you don't have git set up with an SSH key

**Comment by m90** [comment]
Closing this because it's stale and I also start being doubtful this tool should try to work around odd behavior in 7zip at the cost of a highly specific API that possibly eats expected metadata of backups when used incorrectly.

If anyone runs into this problem (unexpected 'PaxHeaders` files) as well, I'd recommend using [`tar.exe`](https://docs.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows) instead of 7zip. It can handle the archives created by this image as expected.
